### ISSUE TITLE
openfortigui crashed with SIGSEGV in QObject::event()

### ISSUE THREAD

**Issue by tmotyl** [theinvisible/openfortigui#100]
the app has crashed when trying to connect.
From syslog:
openfortigui[20072]: segfault at 12b8 ip 0000559b330c1044 sp 00007ffe9a73ec98 error 4 in openfortigui[559b3306e000+ea000]
Code: e2 6b fc ff 66 90 48 83 ec 08 e8 97 f8 01 00 31 ff 48 83 c4 08 e9 1c 58 fc ff 66 90 66 2e 0f 1f 84 00 00 00 00 00 48 8b 7f 10 <ff> a7 a0 12 00 00 66 0f 1f 44 00 00 41 57 41 56 41 55 41 54 55 53

openfortigui 0.8.1.-1
ubuntu 19.10

**Comment by jbaudoux** [comment]
Same issue when main and profile is created as user and app launched with root priviledge:
`
#0  0x0000555555599a3f in qMapLessThanKey<vpnProfile::Origin> (key1=@0x555555667008: vpnProfile::Origin_LOCAL, key2=<error reading variable>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h:71
#1  0x00005555555999ea in QMapNode<vpnProfile::Origin, QString>::lowerBound (this=0x555555666ff0, akey=<error reading variable>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h:155
#2  0x0000555555598e54 in QMapData<vpnProfile::Origin, QString>::findNode (this=0x55555565c5d0, akey=<error reading variable>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h:287
#3  0x00005555555985aa in QMap<vpnProfile::Origin, QString>::operator[] (this=0x7fffffffcbe8, akey=<error reading variable>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h:674
#4  0x000055555559d000 in vpnProfile::readPassword (this=0x0) at vpnprofile.cpp:65
#5  0x000055555559a6c5 in vpnProcess::startVPN (this=0x7fffffffcfd0) at proc/vpnprocess.cpp:112
#6  0x000055555559a211 in vpnProcess::run (this=0x7fffffffcfd0, vpnname=...) at proc/vpnprocess.cpp:62
#7  0x000055555556d7ed in main (argc=6, argv=0x7fffffffe3e8) at main.cpp:166
`

Relaunching the app as root and creating a main and profile as root solved the issue.

**Comment by jbaudoux** [comment]
Duplicate https://github.com/theinvisible/openfortigui/issues/94
