### ISSUE TITLE
Ubuntu 18.04. App always ask password even password was filled.

### ISSUE THREAD

**Issue by linelect** [theinvisible/openfortigui#101]
After ubuntu 18.04 update (not sure that this is true reason but earlier I did not fill password every connect) openFortiGUI 0.7 version always ask password in new window. I've updated openFortiGUI to 0.8.1 version but it did not help.

After edit and adding password using gui I can see in /home/username/.openfortigui/vpnprofiles/nameOfConnection.conf
that password is in the config file:
```
[vpn]
password="encoded_password"
```

But when I try to connect app ask for password:
![image](https://user-images.githubusercontent.com/1188388/70866865-7f910080-1f77-11ea-9e80-06680275e38b.png)

log:
```
Ð³ÑÑÐ´. 15 20:00:51 openfortiGUI::Debug: "start-vpn process::" "connection_name"
Ð³ÑÑÐ´. 15 20:00:51 openfortiGUI::Debug: "start-vpn process::config_file::" "/home/username/.openfortigui/main.conf"
Ð³ÑÑÐ´. 15 20:00:51 openfortiGUI::Debug: vpnProcess::startVPN::slot
Ð³ÑÑÐ´. 15 20:00:51 openfortiGUI::Debug: tiConfVpnProfile::readVpnProfiles() -> vpnprofile found: "/home/username/.openfortigui/vpnprofiles/connection_name.conf"
Ð³ÑÑÐ´. 15 20:00:51 openfortiGUI::Debug: passstore requested from vpn
Ð³ÑÑÐ´. 15 20:00:52 openfortiGUI::Debug: server sent something::
Ð³ÑÑÐ´. 15 20:00:52 openfortiGUI::Debug: server api command2:: 8 ::name:: "connection_name"
Ð³ÑÑÐ´. 15 20:00:54 openfortiGUI::Debug: server sent something::
Ð³ÑÑÐ´. 15 20:00:54 openfortiGUI::Debug: server api command2:: 4 ::name:: "connection_name"
Ð³ÑÑÐ´. 15 20:00:54 openfortiGUI::Debug: vpnWorker::process::slot
Ð³ÑÑÐ´. 15 20:00:54 openfortiGUI::Debug: shutting down vpn process:: "connection_name"
```

How I can fix it?

**Comment by boospy** [comment]
If you create the same connection again, did this solve the problem?

**Comment by linelect** [comment]
> If you create the same connection again, did this solve the problem?

It did not help me.

**Comment by theinvisible** [comment]
Hi, 
the string "passstore requested from vpn" says you are using the password manager which can be enabled/disabled in main preferences. Try disable it and try again.

**Comment by linelect** [comment]
> Hi,
> the string "passstore requested from vpn" says you are using the password manager which can be enabled/disabled in main preferences. Try disable it and try again.

Cannot do that.
![image](https://user-images.githubusercontent.com/1188388/72648691-65867b80-3984-11ea-963a-2e2e2e4af1e8.png)

**Comment by theinvisible** [comment]
Seems like your password manager is broken from your update, please try to fix this first. Also there seems a bug that you cannot disable the password manager when its broken, will look into this. As a workaround you can manually edit your config file in ~/.openfortigui/main.conf and set "use_system_password_store" to false

**Comment by linelect** [comment]
> Seems like your password manager is broken from your update, please try to fix this first. Also there seems a bug that you cannot disable the password manager when its broken, will look into this. As a workaround you can manually edit your config file in ~/.openfortigui/main.conf and set "use_system_password_store" to false

I've fixed problem with password manager but it did not help me.
use_system_password_store is false
Tried re-create connection, no results.

Flow:
1) Edit connection, set password and press save.
2) Go to /home/username/.openfortigui/vpnprofiles/nameOfConnection.conf and see password is filled.
3) Try to connect. Then app shows window 'Please enter you login details'.
4) Open connection for editing and see that passwrod field is empty whereas in config file still present.

**Comment by linelect** [comment]
New portion of logs.
What i did: Just tried edit connection, set password and press save. Then tried connect. App asked password in new window. I closed login window.

**connectionName.log:**
`140581221357568:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:537:
INFO:   Start tunnel.
INFO:   Connected to gateway.
ERROR:  Could not authenticate to gateway (HTTP status code).
INFO:   Closed connection to gateway.
INFO:   Logged out.`


**openfortigui.log:**
`ÑÑÑ. 22 22:17:29 openfortiGUI::Debug: "start-vpn process::" "epi"
ÑÑÑ. 22 22:17:29 openfortiGUI::Debug: "start-vpn process::config_file::" "/home/linelect/.openfortigui/main.conf"
ÑÑÑ. 22 22:17:29 openfortiGUI::Debug: vpnProcess::startVPN::slot
ÑÑÑ. 22 22:17:29 openfortiGUI::Debug: tiConfVpnProfile::readVpnProfiles() -> vpnprofile found: "/home/linelect/.openfortigui/vpnprofiles/epi.conf"
ÑÑÑ. 22 22:17:33 openfortiGUI::Debug: server sent something::
ÑÑÑ. 22 22:17:33 openfortiGUI::Debug: server api command2:: 4 ::name:: "epi"
ÑÑÑ. 22 22:17:33 openfortiGUI::Debug: vpnWorker::process::slot
ÑÑÑ. 22 22:17:33 openfortiGUI::Debug: shutting down vpn process:: "epi"`

**Comment by theinvisible** [comment]
Hi,
seems something wrong with your encryption key or the encrypted data. The problem then is the program can not decode the password and so asks for it.

The best solution would be to start with a fresh profile. To do so close OpenFortiGUI, move your ~/.openfortigui folder somewhere else and start the program again.

**Comment by linelect** [comment]
> Hi,
> seems something wrong with your encryption key or the encrypted data. The problem then is the program can not decode the password and so asks for it.
> 
> The best solution would be to start with a fresh profile. To do so close OpenFortiGUI, move your ~/.openfortigui folder somewhere else and start the program again.

It works! Thank you very much!

**Comment by afperezm** [comment]
> Hi,
> seems something wrong with your encryption key or the encrypted data. The problem then is the program can not decode the password and so asks for it.
> 
> The best solution would be to start with a fresh profile. To do so close OpenFortiGUI, move your ~/.openfortigui folder somewhere else and start the program again.

Using OpenFortiGUI 0.9.0 this solution worked for me, I moved the ~/.openfortigui folder somewhere else and re-started the program, then it asked me a master key to store passwords and I recreated the connection and it worked perfectly.

Thank you!
