### ISSUE TITLE
Suggestion: option to reconnect

### ISSUE THREAD

**Issue by SpyPower** [theinvisible/openfortigui#106]
I have to say your app rocks. It's pretty solid and just works.
I have a suggestion though, to make the app even better.
The company I work at is having a policy to disconnect after X hours of connectivity. Could we have an option to automatically reconnect if disconnected by server? Thanks for your time.

**Comment by tuncenator** [comment]
I would very much like that as well. I have a remote firewall that I sometimes lose connection with. It would definitely help to have it set to "Auto Reconnect".

**Comment by eaydin** [comment]
This would definitely be very useful especially when connecting to VPN's through jump servers.

**Comment by theinvisible** [comment]
There is now an "persistent" mode available in the latest master/dev builds and also will be available on the next release build OpenFortiGUI 0.9.4
