### ISSUE TITLE
Do not override DNSMasq resolv.conf file settings

### ISSUE THREAD

**Issue by raqua** [theinvisible/openfortigui#109]
Hello.

I am on Linux Mint 18 (based on Ubuntu 16.04) and I am using DNSMasq. 
My DNSMasq has custom resolv.conf set in its configuration
resolv-file=/run/raqua-resolv.conf

This works fine when not using DNS or with OpenVPN. I can see in DNSMasq logs that it is loading my configuration correctly. 
But when I start connect with OpenFortiGUI and with DNS setting disabled for the connection, it still does write to file /var/run/dnsmasq/resolv.conf the DNS from VPN service and forces DNSMasq somehow to load and use that config instead of the one I have set up.

**Comment by theinvisible** [comment]
Hi,

as DNS settings are handled by openfortivpn i cannot really help here. Have you tried to use openfortivpn directly and check if the same behaviour?

**Comment by raqua** [comment]
No, I have not tried it. But in some of the older versions it worked when I have "Set DNS" option off. After upgrade it stopped working. I found out that in order for it to work, I needed to enable option 'No peerdns". After that it works as expected. I am not sure what is the difference between those two options. Anyway, I guess this can be closed.
