### ISSUE TITLE
It is not working with ubuntu 20.04 Beta

### ISSUE THREAD

**Issue by lucasapereira** [theinvisible/openfortigui#110]
DEBUG:  Setting min proto version to: 0x301
ERROR:  SSL_connect: error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
You might want to try --insecure-ssl or specify a different --cipher-list

**Comment by filippolmt** [comment]
I have the same problem with the stable version:
ERROR:  SSL_connect: error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
You might want to try --insecure-ssl or specify a different --cipher-list

**Comment by theinvisible** [comment]
Please checkout here: https://hadler.me/2020/04/openfortigui-ubuntu2004-status/

**Comment by prynhart** [comment]
@theinvisible - Is the above URL correct ?  I'm getting: 

![Screen Shot 2020-05-08 at 10 16 34 AM](https://user-images.githubusercontent.com/15762315/81349920-102dd000-9115-11ea-9859-ac27852df82c.png)

**Comment by prynhart** [comment]
Ah - it's just Safari that is unhappy with the cert.  Got there via another browser.  Thank you

**Comment by prynhart** [comment]
Update: Works beautifully with your preview build openfortigui_99.9.1057-1_amd64_focal.deb :-)

**Comment by juan-rey** [comment]
Latests packages did not work for me. But I have tested openfortivpn commandline and I have found a workaround; set **--cipher-list 'DEFAULT:!DH'**

**Comment by GabrieleV** [comment]
Latest build from homepage works. 
To detect ubuntu version, make lsb-release a dep:
```
lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

**Comment by theinvisible** [comment]
This seems also to be more like a generic problem when new openssl versions and older fortigate firmwares are used and unsecure ciphers are disabled. Please check you have a current firmware installed on your fortigate.
