### ISSUE TITLE
got nothing when click connect

### ISSUE THREAD

**Issue by cccnrc** [theinvisible/openfortigui#111]
I downloaded Openfortigui for my Debian9 and installed it, I configured a VPN but whenI try to connect nothing happens, the log file states:

> Apr 22 13:06:08 openfortiGUI::Debug: active-tab:: 0
> Apr 22 13:06:08 openfortiGUI::Debug: start vpn: "AOPR" active-tab:: 0
> Apr 22 13:06:08 openfortiGUI::Debug: Start vpn:: "AOPR"
> Apr 22 13:06:08 openfortiGUI::Debug: add logger "/home/enrico/.openfortigui/main.conf"
> Apr 22 13:06:08 openfortiGUI::Debug: VPN process  "AOPR"  error occurred!
> Apr 22 13:06:08 openfortiGUI::Debug: VPN process  "AOPR"  finished!

Does anybody got a clue of what is going on?

Thank you so much in advance

**Comment by theinvisible** [comment]
You can enable Debug for your VPN profile and see more details.

**Comment by fferraro87** [comment]
i've same problem

**Comment by fferraro87** [comment]
i've solved using beta version (i'm using ubuntu 20.04) and enable Sudo Preserve .env from settings

**Comment by NormanEdance** [comment]
@fferraro87 how to install beta version. I'm also using 20.04.

**Comment by fferraro87** [comment]
@NormanEdance you can follow this https://hadler.me/2020/04/openfortigui-ubuntu2004-status/

**Comment by icdt-ihudson** [comment]
I was able to fix this without using the beta version but just checking the SUDO Preserve Env. setting
