### ISSUE TITLE
GUI not prompting to add a trusted cert

### ISSUE THREAD

**Issue by A-damW** [theinvisible/openfortigui#116]
New installation of: openfortigui_0.9.0-2_amd64_focal.deb
New installation of: Lubuntu 20.04 (In live persistence mode)

Fails immediately upon trying to connect to a known good FortiGate account.

looking at the debug logs suggest that I manually add a trusted cert digest to my config file.

`
DEBUG:  Gateway certificate validation failed.
ERROR:  Gateway certificate validation failed, and the certificate digest is not in the local whitelist. If you trust it, rerun with:
ERROR:      --trusted-cert ba92b71004e9c0459dbb54c60c3fa8a13789d18b6cd614a546c4c52856dc7386
ERROR:  or add this line to your config file:
ERROR:      trusted-cert = ba92b71004e9c0459dbb54c60c3fa8a13789d18b6cd614a546c4c52856dc7386`

Upon copy/pasting the above cert digest into openfortigui, I successfully connect.

Previous versions of openfortigui have prompted to add the trusted cert upon attempting to connect.

**Comment by theinvisible** [comment]
Thanks for your report. There was a typo fixed in openfortivpn so the detection failed. Should work now again with 0.9.0-3 release

**Comment by A-damW** [comment]
I can confirm the gui now prompts to add a cert with 0.9.0-3 release.
