### ISSUE TITLE
Error "/usr/bin/ld: cannot open output file openfortigui: Is a directory" while compiling in Ubuntu 20.04

### ISSUE THREAD

**Issue by faustocarva** [theinvisible/openfortigui#117]
Hi, i was trying to compile the project in Ubuntu 20.04 got this error: 

```
[ 96%] Building CXX object CMakeFiles/openfortigui.dir/openfortigui_autogen/Y2DAEQPLOR/qrc_res.cpp.o
[100%] Linking CXX executable openfortigui
/usr/bin/ld: cannot open output file openfortigui: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/openfortigui.dir/build.make:539: openfortigui] Error 1
make[1]: *** [CMakeFiles/Makefile2:77: CMakeFiles/openfortigui.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

The output file (the executable one) can not be created because in the same directory is a directory with the same name (openfortigui). To correct this i changed the name of the output file to one different from the openfortigui and it worked. Another solution would be to change the source folder name to "src" or any other. 
Thanks in advance.

**Comment by theinvisible** [comment]
Hi, fixed this now by building into separate bin dir.
