### ISSUE TITLE
VPNServer with url IP:PORT/SOMETHING

### ISSUE THREAD

**Issue by mrtsilva** [theinvisible/openfortigui#118]
If you vpn needs to connect to a specific url like
    https://XXX.XXX.XXX.XXX:443/VPNCLIENTS
It always gives this error:
    openfortiGUI::Warning: DNS lookup error:  "Invalid hostname"
Thanks

**Comment by theinvisible** [comment]
Hi, this is not how it works, you must split your information.
VPN-Server = XXX.XXX.XXX.XXX
VPN-Port = 443
Realm = VPNCLIENTS
