### ISSUE TITLE
Using translated versions

### ISSUE THREAD

**Issue by aseques** [theinvisible/openfortigui#122]
Reading on the website, I see that openfortigui is translated into several languages, I coudln't see where should one change the language settings?

**Comment by theinvisible** [comment]
The language is fetched from the system locale and cannot be changed manually. To force a language you can set the LC_ALL variable to your desired language: LC_ALL="C" openfortigui

**Comment by aseques** [comment]
Thanks I configured my system into my language and it started being displayed localized. Thanks a  lot for your help
