### ISSUE TITLE
VPN-Groups Disappear

### ISSUE THREAD

**Issue by luisrdzruiz** [theinvisible/openfortigui#125]
OS: Ubuntu
OS Version: 20.04
openfortigui version: 0.9.1

Description:
When upgrade to version 0.9.1 the vpn-groups that I created disappearing, I tried to create again but not appear them.

In the logs throws this warning:
jul. 1 10:24:39 openfortiGUI::Debug: tiConfVpnGroups::readVpnGroups() -> vpngroup found: "/home/luisrdzruiz/.openfortigui/vpngroups/RAGASA.conf"
jul. 1 10:24:39 openfortiGUI::Warning: tiConfVpnProfile::readVpnGroups() -> vpngroup has not a valid name, skip loading:  "/home/luisrdzruiz/.openfortigui/vpngroups/RAGASA.conf"

**Comment by theinvisible** [comment]
Should be fixed in latest git commit and next release.
