### ISSUE TITLE
Missing Icon after connecting in Linux Mint 20 on boot

### ISSUE THREAD

**Issue by dogmaxpeppe** [theinvisible/openfortigui#126]
After upgrading to Linux Mint 20 (it's equivalent to Ubuntu 20.04), and installed 0.90 version of openfortigui, icon after connection will be replaced by an icon like this:

[Icon](https://ibb.co/3pX8Cn0)

In logs it gives me an error that I think is related to missing icon:

`lug 10 14:03:05 openfortiGUI::Warning: load glyph failed err=6 face=0x55dcd13cf100, glyph=65535`

The strange thing it's that this error occurs ONLY when I start OpenFortiGUI on boot. If I close and reopen the application, it gives me the correct icon.

**Comment by ianw1974** [comment]
To me it happens even without starting it at boot.  When the VPN connects it gets a blue info icon, and then after disconnecting the VPN it goes to the no entry sign as the original poster mentioned.

**Comment by Trapizomba** [comment]
![openfortigui_0 9 0-3_amd64_focal-missing-icon](https://user-images.githubusercontent.com/4828145/88055204-f78a5f00-cb34-11ea-9915-6654a12a94d9.png)

**Comment by Trapizomba** [comment]
> To me it happens even without starting it at boot. The icon is the correct green one until you connect a VPN. When the VPN connects it gets a blue info icon and then after a few seconds the icon goes to the no entry sign as the original poster mentioned.

Same here...

**Comment by ianw1974** [comment]
Today I have noticed this problem has disappeared for me.  I think the control of the icons was from libnotify.  I'm still running 0.9.0-3 release and seems to be fine now.

**Comment by theinvisible** [comment]
Thanks, as it seems not related to OpenfortiGUI i will close this issue.
