### ISSUE TITLE
ERROR - Disable Network

### ISSUE THREAD

**Issue by BrunoGiubilei** [theinvisible/openfortigui#129]
I use openfortigui 0.8.2-1
My operating system is Manjaro
Linux 54 kernel version 5.4.52-1

When I go to turn off the application, with the right button, turn off, the internet stops working. Then I turn off WIFI and turn it back on and it works again.

**Comment by theinvisible** [comment]
Hi, please try first with latest version 0.9.2, maybe you can also check if this happens with openfortivpn. Seems like your default gateway is removed by accident.

**Comment by elliotwutingfeng** [comment]
I also have the exact same issue with version openfortigui version 0.9.2.

My OS is 5.7.19-2-MANJARO.

**Comment by theinvisible** [comment]
Thanks for offering a solution, i will close this now.
