### ISSUE TITLE
openFortiGUI 0.9.2 opens changelog each time it is opened

### ISSUE THREAD

**Issue by digitalkram** [theinvisible/openfortigui#131]
Hello,

openFortiGUI 0.9.2 opens changelog each time it is opened (started after the last update through package manager) .

Is that the intended behviour or is it supposed to happen only at the first startup after an upgrade (no checkbox to skip it is existing).

Cheers

**Comment by theinvisible** [comment]
Hi,

this is indeed not intended behavior. Please check if your ~/.openfortigui/main.conf file is writable by the user executing OpenFortiGUI. If not, the changelog read number cannot be incremented.

**Comment by digitalkram** [comment]
hi @theinvisible 

Thanks a lot for your reply. Actually main.conf is not writable by my user. It is 664 and owned by root... All other files are user owned. I'll re-own it. I wonder how this happened? Or is it by design?
