### ISSUE TITLE
Trim hostname, username, etc when saving VPN details

### ISSUE THREAD

**Issue by rm-hull** [theinvisible/openfortigui#136]
I had a situation where I had saved a VPN configuration with a single space after the hostname, and it refused to connect with the following logging:
```
INFO:   Start tunnel.
INFO:   Closed connection to gateway.
ERROR:  connect: Connection refused
INFO:   Could not log out.
```
I knew the configuration worked as it was copied from my openfortivpn config. 

It might be worth trimming whitespace characters from fields like the host before using them or saving them.

**Comment by theinvisible** [comment]
Thanks, its fixed in current master branch and next release
