### ISSUE TITLE
Not working in Linux Mint 20

### ISSUE THREAD

**Issue by anat0lius** [theinvisible/openfortigui#137]
Using the latest build from repo. It does nothing when I try to connect to the vpn. 

I've found this in the logs:
`sept. 10 19:18:03 openfortiGUI::Debug: OS not affected by SUDO-Preserve-Env fix or no supported OS found, osname:: "ulyana"`

I've upgraded from Linux Mint 19 to 20 (Cinnamon) with Kernel 5.4.0-47-generic.

**Comment by ianw1974** [comment]
Hi, I'm using it on Linux Mint 20 without problems.  Go into settings and enable this option:

```
SUDO -E option
```

make sure that box is ticked.  Save and then try again.  You may want to exit openfortigui and open it again just to be sure as not sure if it is required to fully close it or not.

**Comment by anat0lius** [comment]
Thanks, now it works.
I didn't notice that option, I guess it was added in a recent build.
