### ISSUE TITLE
Tray icon missing on Ubuntu 20.10 when using gnome Autostart

### ISSUE THREAD

**Issue by doudz** [theinvisible/openfortigui#139]
The tray icon is missing on Ubuntu 20.10, it was working good on Ubuntu 20.04

Could you add support for Ubuntu 20.10 ?

**Comment by doudz** [comment]
I confirm that just recompiling on Ubuntu 20.10 fix the problem

```
sudo apt install build-essential qt5-default libssl-dev qt5keychain-dev
git clone https://github.com/theinvisible/openfortigui.git
cd openfortigui
git submodule init
git submodule update
qmake
make -j4
sudo cp openfortigui/openfortigui /usr/bin/openfortigui
```

**Comment by dberniell** [comment]
Recompiling dosn't work for me.

**Comment by doudz** [comment]
you're right, it worked at first but not anymore after reboot...

**Comment by doudz** [comment]
it's a bit off topic but since the problem is "only" the gui, maybe it's possible to rewrite the gui in Python so it could work out of the box on any system with python and pyqt5 ? (any Ubuntu)

**Comment by doudz** [comment]
Looking deeper, I found that the problem is the autostart I made, I have put the app in "Startup Applications" and it was working on previous Ubuntu release but now on Ubuntu 20.10 the app starts but the tray icon is missing.
If I launch the application manually, it works

So I just delay the autostart by add `X-GNOME-Autostart-Delay=60`  in `~/.config/autostart/openfortigui.desktop` and now it works

**Comment by dberniell** [comment]
In my case it isn't still showing. I don't have ~/.config/autostart/openfortigui.desktop file or launching the app manually doesn't work either.

**Comment by doudz** [comment]
Stange, I tried to re-install the deb file and it works manually or with autostart and delay

**Comment by dberniell** [comment]
Yes strange, I also tried to reinstall deb file version 0.9.3 and didn't work

**Comment by dberniell** [comment]
Finally sovled adding gnome tray icons extension
