### ISSUE TITLE
Attempts to re-launch openfortigui sometimes fails

### ISSUE THREAD

**Issue by elliotwutingfeng** [theinvisible/openfortigui#140]
Sometimes after disconnecting from an openfortigui VPN connection and exiting the application for the first time, attempting to launch openfortigui again will fail with no error messages. Attempts to kill the pid of openfortigui have no effect. The only workaround is to logout and login again.

OS & Kernel Version: 5.4.72-1-MANJARO x86_64 20.1.2 Mikah
Desktop Environment: GNOME Shell 3.36.6

**Comment by theinvisible** [comment]
Sorry, i will not support other Distros than Ubuntu. As also nobody else answered here i will close this.
