### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by NaimadTheOne** [theinvisible/openfortigui#142]
Detail in printscreen. It happens already multiple times.

![image](https://user-images.githubusercontent.com/33543835/100655467-9c227600-334b-11eb-82f2-80255fb96155.png)

**Comment by theinvisible** [comment]
Hi, there are only official builds for Ubuntu LTS available. If you are using LTS packages on the wrong distro it can bust must not work. But you can still provider more details, please enable Debug log in Settings/VPN and post the log output here.

**Comment by NaimadTheOne** [comment]
Error is before GUI is activated. I dont see anything usefull in log

![image](https://user-images.githubusercontent.com/33543835/108553483-061b3d80-72f3-11eb-9c22-6bfddf7f1d65.png)

**Comment by theinvisible** [comment]
Please make sure to disable debug option in Client and VPN setting for productive use. Otherwise it spams the logs with debug information and can cause an segfault.
