### ISSUE TITLE
Continually Prompted for OTP which isn't configured

### ISSUE THREAD

**Issue by rustyjarz** [theinvisible/openfortigui#144]
Hi,

Installed the Ubuntu 20.04 OpenFortiGUI 0.9.3 64bit and I'm continually prompted for OTP for connections which don't require OTP, and the option to prompt OTP in the configuration of the connection is not configured.

**Comment by theinvisible** [comment]
Hi, please enable debug log in Settings and VPN and post the output here, thanks.
