### ISSUE TITLE
Segfault when starting from command line

### ISSUE THREAD

**Issue by bbuhtig** [theinvisible/openfortigui#145]
After upgrade to Ubuntu 20.04, my previously working command

`sudo openfortigui --start-vpn --vpn-name MY_VPN` 

seg-faulted. I straced the command and it apparently didn't find the VPN profile in the user dir anymore. After symlinking `/root/.openfortigui/vpnprofiles` to the vpnprofiles directory in the user dir the command worked again.

**Comment by theinvisible** [comment]
Hi, this is related to a sudo change in preserving environments. You must use "sudo -E openfortigui" and it should work again.

**Comment by vr-thi** [comment]
I can confirm that `sudo -E ...` works.

Thank you very much.

**Comment by bbuhtig** [comment]
I confirm that `sudo -E ...` works.

Thank you very much.
