### ISSUE TITLE
Dialog is too tall to fit on screen

### ISSUE THREAD

**Issue by edumco** [theinvisible/openfortigui#147]
The Dialog uses too much vertical space. On screens with 1366x768 on Ubuntu the dialog does not fit in the screen

![Captura de tela de 2021-01-15 15-00-38](https://user-images.githubusercontent.com/21086024/104762509-3e06f200-5743-11eb-9849-46f4abb70f10.png)

**Comment by theinvisible** [comment]
Thanks, i adjusted the minimum size for some windows. Is submitted now in master branche and available in next release.
