### ISSUE TITLE
openfortigui install

### ISSUE THREAD

**Issue by vhuezo** [theinvisible/openfortigui#148]
I have it installed on my Ubuntu 
![2021-03-30_15-11](https://user-images.githubusercontent.com/41808201/113059337-8fccef00-916c-11eb-8a75-471c8ebc7d84.png)

and I wanted to Install it in Opensuse.

How do I install it in OpenSuse openSUSE-Leap-15.2?

**Comment by theinvisible** [comment]
Hi, there are no prebuild packages for OpenSuse, I only support Ubuntu LTS.

So your options are to build from source (see instruction from https://hadler.me/linux/openfortigui/) or maybe someone provided a prebuild package you can install.
