### ISSUE TITLE
Feature Request - Searchpossibility

### ISSUE THREAD

**Issue by boospy** [theinvisible/openfortigui#15]
Hello, 

i would be really fine that in openfortigui is possible to search for vpn's on writeing in a searchmask. :) :) :) A plugin for Krunner would be also nice :+1: 

Thanks and Best Regards

**Comment by theinvisible** [comment]
Search is now included in version 0.4.0.

Krunner can be considered for the future. : )

**Comment by boospy** [comment]
Very thanks and good work! I'd like the new searchfeature really mutch :+1:
