### ISSUE TITLE
No connection using Ubuntu 20.04

### ISSUE THREAD

**Issue by tirohia** [theinvisible/openfortigui#153]
Upgraded to Mint 20.2 (Ubuntu 20.04) yesterday. The prebuilt package for Ubuntu 20.04 (openfortigui_0.9.4-1_amd64_focal) doesn't appear to be working. The applications starts, all the settings that worked two days ago are there, but any attempt to connect results in no action. 

There's no error messages that I can see, so I don't know what information I can give you that would help in debugging this. Happy to run anything to help identify the cause though. 

Kernel: 5.4.0-77-generic x86_64 
bits: 64 
compiler: gcc 
v: 9.3.0 
Desktop: Cinnamon 5.0.5 
wm: muffin 
dm: LightDM 
Distro: Linux Mint 20.2 Uma 
base: Ubuntu 20.04 focal

**Comment by theinvisible** [comment]
Hi,

make sure "SUDO -E" option is enabled in settings which is required for new Debian/Ubuntus. For further debugging enable Debug logging in Settings and VPN-Settings and check logs.

**Comment by tirohia** [comment]
There is no option for setting "SUDO -E" in the settings. 
The options to enable logging for VPN, Telemetry and Updates are visible but unable to be selected. 

![openforticlient](https://user-images.githubusercontent.com/4374479/131579764-69819afb-7660-4db0-bddb-7f4899cbf25f.png)

**Comment by theinvisible** [comment]
Indeed, for support please check support.fortinet.com
