### ISSUE TITLE
Preshared key VPN support

### ISSUE THREAD

**Issue by OscarBeiro** [theinvisible/openfortigui#154]
Thanks for your work, this looks exactly what I was looking for. :)

Unfortunately, I cannot see how to add a Pre-shared key on my VPN Cli. 
Is this option at least in the roadmap? Or maybe it has a different name (I've tried with Realmand doesn't seem to work)

Regards,

**Comment by theinvisible** [comment]
preshared key is only available for IPSEC-VPN, this client only supports SSLVPN. For official clients for IPSEC check forticlient.com
