### ISSUE TITLE
Hide Gui 

### ISSUE THREAD

**Issue by tvk7** [theinvisible/openfortigui#17]
If I say hide in the gui, where does it hide (forever in the background?) Can I get the window back?

**Comment by cdysthe** [comment]
I reopen it from the system tray. Don't you have some sort of tray for applications?

**Comment by tvk7** [comment]
Hi, I test this under Ubuntu Gnome 16.04. Under your hiding functions is working. May there is a Gnome Shell Extension which catch this up? Since Canonical decided to switch completely to Gnome you should may take a look at it. But I can't find it anywhere. Thanks

**Comment by theinvisible** [comment]
Hello,

thanks for your request.

I mainly test with Ubuntu LTS-releases so i did not had the problem yet. I think this is just a problem how Gnome displays the trayicons. If I have time i can fire up a VM later to investigate this problem.

Thanks & Cheers
Rene

**Comment by tvk7** [comment]
Cool, I have no experience about Gnome programming. But an easy solution could be looking into the Extension API. To have something like the other Gnome Extensions, which you could probably extend to have for example directly connect/disconnect, quick status. etc, either way thanks.

**Comment by theinvisible** [comment]
Hi,

there is no extension required, the "tray" should be supported by almost any advanced desktop environment.

I have also tested now with Ubuntu 17.10, the tray icon is there on the topright corner.

Cheers

**Comment by thedarkwinter** [comment]
This might or might not help, but in 17.10 this was fine for me until I switched from gnome3 on wayland to gnome3 on xorg, now the icon doesn't appear. Admittedly, I have struggled with the tray in 17.10, and no combination of extensions seems to resolve it completely, but with 18.04 switching (back to) xorg, might be worth looking into...
