### ISSUE TITLE
OFG versions in iteas repo supercede those mentioned here and on hadler.me

### ISSUE THREAD

**Issue by BrandonNolet** [theinvisible/openfortigui#174]
In the screenshot below, you'll see that versions 0.9.6 and 0.9.7 of openfortigui have been put up onto the apt.iteas.at repo ([Packages file for focal](https://apt.iteas.at/iteas/dists/focal/main/binary-amd64/Packages)).

Since much of our IT crew is not on Linux, we don't have the notification that the new version was released and this is causing issues with some of our employees. 

Any reason why versions are being released without a changelog, notification, publication, whathaveyou?

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/88151475/185468522-eb55761e-4825-473a-b46b-91bbaad5887f.png">

**Comment by theinvisible** [comment]
Hi,

this project ist mostly maintained in my (spare) freetime and was quite lazy to write announcements for new releases the last time. 

Seems like its getting better now again, you can also always check the tags page for new releases: https://github.com/theinvisible/openfortigui/tags

.deb releases should always be "stable" as we use it in our Org and also for customers
