### ISSUE TITLE
Not Working On Linux Mint 21

### ISSUE THREAD

**Issue by kydner** [theinvisible/openfortigui#175]
Selecting previously unselected package openfortigui.
(Reading database ... 316683 files and directories currently installed.)
Preparing to unpack openfortigui_0.9.5-1_amd64_focal.deb ...
Unpacking openfortigui (0.9.5-1) ...
dpkg: dependency problems prevent configuration of openfortigui:
 openfortigui depends on libqt5keychain1 (>= 0.7.0); however:
  Package libqt5keychain1 is not installed.
 openfortigui depends on libssl1.1 (>= 1.1.0); however:
  Package libssl1.1 is not installed.

dpkg: error processing package openfortigui (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for desktop-file-utils (0.26+mint1+vanessa) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Errors were encountered while processing:
 openfortigui

**Comment by elead-ley** [comment]
install libssl1.1 from deb file from here:
http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb

**Comment by kydner** [comment]
Ok thanks, its solve
