### ISSUE TITLE
After closing the window endless notification for Barracuda VPNs.

### ISSUE THREAD

**Issue by boospy** [theinvisible/openfortigui#177]
Hello all, 

i'am using here KDE Neon 20.04 with OpenFortigui 0.9.7-2. If i connect to an barracuda vpn, and i minimize the windows, everything is ok. But if i close it to the systemtray, i get endless notification. [Video attached](https://darkdevil.osit.cc/nextcloud/s/DAaPLNTJR3oFjN7)

**Comment by theinvisible** [comment]
Fixed in latest release ; )

**Comment by boospy** [comment]
Is now back again. Version 0.9.9-2

**Comment by boospy** [comment]
🤔

**Comment by theinvisible** [comment]
Try new version 0.9.10
