### ISSUE TITLE
Nothing happens when I click connect

### ISSUE THREAD

**Issue by insanerwayner** [theinvisible/openfortigui#18]
I've configured the VPN Settings but when I click any of the "Connect" buttons, nothing happens. No errors, just no results.

**Comment by theinvisible** [comment]
Hello,

please enable debug log in settings and your VPN-profiles and post your log output here.

**Comment by drcoll** [comment]
I second this. Debug is enabled in settings, and yet no logs are being produced.

**Comment by theinvisible** [comment]
Maybe there is something wrong with your sudo settings.

Please also check your system logs and try if you can start openfortigui with sudo.

**Comment by pozgo** [comment]
Why did you guys close this issue? It's not close to resolved, is it? Word "maybe" is not really giving any specific answer. Please reopen. 

PS. The problem is that there is no logs to follow to find what might be the issue.

**Comment by diegombeltran** [comment]
Same here with Debian 9. I tried the client months ago and it has the same exact issue.

**Comment by flamontagne** [comment]
Any chance this issue gets resolved? I'm on Q4OS (debian stretch) and I'm experiencing the same problem. When I click connect it says "connecting" then goes back to "disconnected" after awhile. No logs are being written.

I'm running openfortigui with sudo.

**Comment by theinvisible** [comment]
Thanks for your request.

I dont have Debian Stretch running here, but you can debug on yourself. Just follow the debug section here: https://hadler.me/linux/openfortigui/ 

More interesting for you is to start the VPN via console and check the output: `sudo /usr/bin/openfortigui –start-vpn –vpn-name [yourvpnname] –main-config ‘/home/[yourusername]/.openfortigui/main.conf’`

**Comment by callum-b** [comment]
Hi,

I have a similar issue where pressing "connect" did nothing. 
However using `sudo openfortigui` fixes it, I can connect no problem when I specify this.

I can supply logs if needed but personally I have no idea where this could be coming from.

**Comment by leo2d** [comment]
I had the same issue here. 

I'm using Kubuntu and Open Forti GUI v0.8.2

I solved that issue by enabling this option on settings and restart the app:

![Screenshot_20200327_093928](https://user-images.githubusercontent.com/28194654/77757106-5882aa00-700f-11ea-86d2-2415f40b5a95.png)

**Comment by vinter45** [comment]
May be your password was changed. So update the password.

**Comment by bryanpedini** [comment]
@leo2d's solution worked for me, thank you!

**Comment by caiocutrim** [comment]
same issue in archlinux.

**Comment by ThiagoSchetini** [comment]
same issue in archlinux here. "solved" with the sudo option checked, but trying to understand if the problem now is from the server or with the app.

**Comment by pokatomnik** [comment]
@leo2d Thanks a lot! Works finally!

**Comment by ShahFaisalIslam** [comment]
> I had the same issue here.
> 
> I'm using Kubuntu and Open Forti GUI v0.8.2
> 
> I solved that issue by enabling this option on settings and restart the app:
> 
> ![Screenshot_20200327_093928](https://user-images.githubusercontent.com/28194654/77757106-5882aa00-700f-11ea-86d2-2415f40b5a95.png)

This really worked! Thanks
