### ISSUE TITLE
2FA on Okta

### ISSUE THREAD

**Issue by fabianofnl** [theinvisible/openfortigui#180]
Hi guys,
I'd like to know if OpenFortiGui has improvements about 2FA for OKTA ?

When I use another VPN application (on Windows for example), after click on connect a popup appears for me with Okta auth parameters, but on OpenFortuGui this is not happened.

**Comment by theinvisible** [comment]
Hi,
we are not using OKTA so there is no plan to integrate it. 

But still PR are welcome.
