### ISSUE TITLE
Ubuntu 22.04 libssl1.1 dependency problem

### ISSUE THREAD

**Issue by potito-coluccelli** [theinvisible/openfortigui#181]
Hi, 
I'm trying to install openfortigui on ubuntu 22.04, but I have this error:
#sudo dpkg -i openfortigui_0.9.8-1_amd64_focal.deb 

Selecting previously unselected package openfortigui.
(Reading database ... 298344 files and directories currently installed.)
Preparing to unpack openfortigui_0.9.8-1_amd64_focal.deb ...
Unpacking openfortigui (0.9.8-1) ...
dpkg: dependency problems prevent configuration of openfortigui:
 openfortigui depends on libssl1.1 (>= 1.1.0); however:
  Package libssl1.1 is not installed.
dpkg: error processing package openfortigui (--install):
 dependency problems - leaving unconfigured
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu3) ...
Errors were encountered while processing:
 openfortigui

Plus, When I try to install something with apt I get this error:

You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 **openfortigui : Depends: libssl1.1 (>= 1.1.0) but it is not installable**
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

It seems that libssl1.1 is not available in the ubuntu repo anymore.

**Comment by theinvisible** [comment]
22.04 has codename jammy, you are trying to install the focal package

https://apt.iteas.at/iteas/pool/main/o/openfortigui/openfortigui_0.9.8-1_amd64_jammy.deb

**Comment by theinvisible** [comment]
Yeah thanks, its fixed now ; )
