### ISSUE TITLE
Add Debian bookworm

### ISSUE THREAD

**Issue by williamdes** [theinvisible/openfortigui#189]
Please support Debian bookworm

Also, about https://bugs.debian.org/888518

Would you like to help me so we can get openfortigui into the next Debian ?

**Comment by Trikenstein** [comment]
Debian 12 has support for Fortinet SSLVPN:

```
apt install openfortivpn
```

Then Settings/Connection, create a new connection of type Fortinet SSLVPN

![NetworkManager_01_Create_Fortinet_SSLVPN](https://github.com/theinvisible/openfortigui/assets/72353094/62c1c444-b37a-43c4-8346-239cc5d52f57)

![NetworkManager_02_FortiVPN_properties](https://github.com/theinvisible/openfortigui/assets/72353094/eebf792f-f2a8-4caa-b37f-3423d9ac7765)

![NetworkManager_03_Connect_VPN](https://github.com/theinvisible/openfortigui/assets/72353094/da17b38b-a91e-4246-b9b8-9c6c45797d15)

**Comment by theinvisible** [comment]
Bookworm packages are available now on apt.iteas.at repo server
