### ISSUE TITLE
No information about expired password

### ISSUE THREAD

**Issue by raqua** [theinvisible/openfortigui#19]
Hi,

my password expired recently and I could not connect but GUI gave me no information about it. I thing this info should be shown to user, I had to dig for the reasons why I suddenly can not connect.

**Comment by theinvisible** [comment]
Hi,

do you have any log messages for this case? Do you use LDAP or AD-Auth on your Fortigate?

We never had this case here and i also dont know if the Fortigate is reporting a expired password. Maybe you can try again, enable Debug log in your VPN setting and post any relevant error messages.

Thanks

**Comment by raqua** [comment]
Hi, 

I have no idea of the Fortigate settings, is there a way I can find this out? It seems that there are some logs on ~/.openfortigui folder that show debug info log level. Is that enough for the future or do I need to enable it somewhere as you suggested? 
I think the password expiration period is 3 months, so next time this happens, I could provide logs.

**Comment by theinvisible** [comment]
You can ask your firewall administrator for details.

You can access the logs also from gui, just right click a VPN and choose Logs. Inside each VPN configuration you can also activate "Debug" for more verbose log.

But would be nice to know if you are using LDAP, AD, RADIUS or something else.

**Comment by theinvisible** [comment]
Any information here? Otherwise i will close this issue.

**Comment by raqua** [comment]
My password have not expired since this happened, so I have no new info. I have bookmarked this thread and once my password expires I will provide the logs. So I will prefer to keep it open.

**Comment by theinvisible** [comment]
Hi,

to keep things clean i will close this issue. You are welcome to open a new issue when you have a status update for your case.
