### ISSUE TITLE
Add support for Ubuntu 23.04 (Lunar Lobster)

### ISSUE THREAD

**Issue by prashanth-nani** [theinvisible/openfortigui#191]
Hello, I am a user of OpenfortiGUI and I would like to request support for the latest version of Ubuntu, version 23.04.

I have been using OpenfortiGUI on my previous Ubuntu installations, and it has been an essential tool for managing my VPN connections. However, I recently upgraded my system to Ubuntu 23.04, and I noticed that OpenfortiGUI is not currently supported.

I believe that adding support for Ubuntu 23.04 would greatly benefit other users who have upgraded or will upgrade to this version. I kindly request that the development team add support for Ubuntu 23.04 as soon as possible.

Thank you for your hard work and for creating such a valuable tool.

**Comment by zaa730Sight** [comment]
Yes please, I'd also like to add another +1 to this request

**Comment by theinvisible** [comment]
Hi, you can use the Ubuntu 22.04 Jammy packages, its working fine and i am also using it that way.
