### ISSUE TITLE
Option to start in system tray.

### ISSUE THREAD

**Issue by cdysthe** [theinvisible/openfortigui#2]
Hi,

I now have openfortigui run at all times on my work laptop. It would be great with an option to have the application open in system tray

**Comment by boospy** [comment]
Yes that would be great.

**Comment by boospy** [comment]
Package updated, so please test it!

**Comment by cdysthe** [comment]
I've tried the new package and I cannot see the where I set the app to start at login in the system tray. Or just start in system tray if I set kde/gnome (Insert random DE) to start the app at login.

**Comment by boospy** [comment]
Add the to your system autostart, that is working. Don't forget to set the "Minimized start" option in the fortigui.

**Comment by cdysthe** [comment]
Thanks. The problem is that I can not find the "Minimized start" option in forigui. I downloaded the deb and reinstalled, but can not find that option. Sorry if I am missing something obvious! :) I am running openFortiGUI 0.2.10-dev .

**Comment by boospy** [comment]
![screenshot_20170516_221738](https://cloud.githubusercontent.com/assets/7432752/26126378/a1919980-3a85-11e7-85fa-af68df7e4836.png)

**Comment by cdysthe** [comment]
I do not have that setting. I only have Debug and AES Key. Is it this package: https://hadler.me/files/openfortigui/openfortigui_0.2.10-1_amd64.deb  ? I will also try to purge and reinstall to see if that helps.

**Comment by boospy** [comment]
Oh ok, this site is not updated. Us the repo, there are always the newest packages: http://styrion.at/apt/

**Comment by cdysthe** [comment]
Thanks! Got it! :)
