### ISSUE TITLE
IPSEC support

### ISSUE THREAD

**Issue by SoftExpert** [theinvisible/openfortigui#20]
Hello,

It would be great to allow IPSEC connections as well - since Fortinet does such a poor job on providing a Linux client. 
Would that be difficult to implement?

Thank you for the great work, by the way !

Best regards,
SoftExpert

**Comment by theinvisible** [comment]
Hi,

this project fully relies on openfortivpn to establish an VPN https://github.com/adrienverge/openfortivpn

If you want a feature request please open an issue there. At this time openfortivpn only supports SSLVPN. For general IPSEC support there are also other projects available like libreswan: https://libreswan.org/

Cheers
Rene
