### ISSUE TITLE
no cookie support?

### ISSUE THREAD

**Issue by benoitc** [theinvisible/openfortigui#23]
I can't connect to a vpn, each time I am trying it is logging out. I get the following logs:

```
INFO:   Connected to gateway.
ERROR:  Could not authenticate to gateway (No cookie given).
INFO:   Closed connection to gateway.
INFO:   Logged out.
```

**Comment by theinvisible** [comment]
Looks like there is something wrong with your vpn configuration. Maybe you need additional login data or a certificate. You can also try the latest version now (0.4.0) but i think the problem is your authentication.

**Comment by s19n** [comment]
I am seeing this as well, using same credentials the windows version of the client works correctly, so I am wondering what exactly could be wrong...
