### ISSUE TITLE
macOS support 

### ISSUE THREAD

**Issue by fabiogermann** [theinvisible/openfortigui#25]
As openfortivpn is available for macOS, is this also the case for the GUI. I know QT is also available for macOS but haven't seen it mentioned here.

**Comment by theinvisible** [comment]
Hi, i have no Apple device here for testing this. Maybe someone else can.

**Comment by SkyCrawl** [comment]
@fabiogermann 

If still relevant, you could try to have a look [here](https://github.com/theinvisible/openfortigui/issues/56).
