### ISSUE TITLE
Version 0.2.12-1 is broken 

### ISSUE THREAD

**Issue by cdysthe** [theinvisible/openfortigui#3]
I tried to install and run 0.2.12-1 but I'm not able to set up a connection with it. I click connect but I never get a connection. I get the red disconnected indication after a second or so. 0.2.11 works well. 

_Sent from my BLU Life One X2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by boospy** [comment]
Important: Since version 0.2.12 the encoding of AES-encrypted passwords has changed because of a change of the upstream AES-library. You must reset all passwords for your VPN-profiles again to work, sorry for the inconveniences. https://github.com/Skycoder42/QTinyAes/issues/1
