### ISSUE TITLE
Initial Launch of openfortigui opens changelog and wizard behind main window

### ISSUE THREAD

**Issue by matjam** [theinvisible/openfortigui#32]
Problem:

Initial Launch of openfortigui opens changelog and wizard behind main window. This is confusing because you expect to be able to click on controls in the main window and they are not responsive as the other windows are modal.

Affects: 0.6.0 and 0.6.1-dev

**Comment by theinvisible** [comment]
Thanks, there was now code added to put setup wizard/changelog window in foreground.
