### ISSUE TITLE
No contextual menu for sytem-tray icon in Ubuntu Mate 18.04

### ISSUE THREAD

**Issue by stremblay** [theinvisible/openfortigui#35]
Hello, I have just installed Ubuntu Mate v18.04 in a Virtualbox VM. It looks like the contextual menu for the system tray icon is not displaying or shows up empty when I click on the icon. I used Mate tweak to modify my desktop a bit and basically changed my panel layout as "Redmond". That's about the only change I made other than installing a different theme in the Appearance Preferences.

Also, if I close the main window I am left with only the icon in the system tray. If I double-click, the main window does not come back. And I have no other way to make the main window reappear. I am then forced to kill the app on the command line, but then the process becomes defunct.

Let me know if there is anything else I can do to provide you with more info.

I have attached a screenshot to show you what it looks like.
![capture](https://user-images.githubusercontent.com/413282/39938981-be669f2a-5522-11e8-99b5-969c594a1cba.JPG)

**Comment by theinvisible** [comment]
Hi, thanks for your report.

As i only test for and use KDE (Neon) and GNOME/Unity i can not really help you with your problem.
Have you enabled the use of password manager store (GNOME-Keyring/KWallet) in OpenFortiGUI? If yes please try to disable and restart OpenFortiGUI.

I have seen weird behavior when this feature was enabled on a GNOME/Unity like desktop.

Generally the tray feature should work across all desktop environments that the Qt library supports.

Thanks
Rene

**Comment by stremblay** [comment]
Hi Rene,

That totally did the trick. I disabled the use of the keyring/password manager and now the contextual menu appears in the system tray. That's so weird.

Thank you,

Stéphane

**Comment by theinvisible** [comment]
Hi,

yes this bug is already known and i am working on it. Hope i can fix it soonest. 

Regards
Rene

**Comment by theinvisible** [comment]
Hi,

the latest released version 0.7.0 should now fix this issue, please give it a try.

Cheers
