### ISSUE TITLE
Nothing happens when clicked connect

### ISSUE THREAD

**Issue by pozgo** [theinvisible/openfortigui#37]
Same issue as #18 

Absolutely nothing happens and whats in logs below:

Run as root to make sure no permissions issue. 

`/root/.openfortigui/logs/vpn/CONFIG_NAME.log`

```
ERROR:  getaddrinfo: Name or service not known
INFO:   Closed connection to gateway.
ERROR:  connect: Connection refused
INFO:   Could not log out.
```
Connection refused is a BS since I'm using bash commands to connect without any issues. 
So I assume some problem with the way you process data when connecting

general log `/root/.openfortigui/logs/openfortigui.log`

```
May 13 18:44:28 openfortiGUI::Debug: tiConfVpnProfile::readVpnProfiles() -> vpnprofile found: "/root/.openfortigui/vpnprofiles/CONFIG_NAME.conf"
May 13 18:44:28 openfortiGUI::Debug: MainWindow::refreshVpnProfileList() -> vpnprofiles found:: "CONFIG_NAME"
May 13 18:44:30 openfortiGUI::Debug: active-tab:: 0
May 13 18:44:30 openfortiGUI::Debug: start vpn: "CONFIG_NAME" active-tab:: 0
```
Please do not close with "maybe" statements ;)

**Comment by queirozfcom** [comment]
I had this issue, fixed by running openfortigui with `sudo`

**Comment by kloneets** [comment]
Same issue for me on ubuntu 21.04. Works only with sudo. Maybe some kind of group/permission problems?
