### ISSUE TITLE
License problem

### ISSUE THREAD

**Issue by adrienverge** [theinvisible/openfortigui#39]
Hi,

First, good job, nice wrapper around openfortivpn :+1:

However, I haven't seen any license information in this repo.

Since openfortivpn is licensed under GPL version 3 (+ an OpenSSL exception), openfortigui *must* be distributed under the same conditions, i.e. a GPLv3-compatible license. This means:
- A license file needs to be added to the repo, and available from project root. You could copy [openfortivpn license file](https://github.com/adrienverge/openfortivpn/blob/master/LICENSE), which of course is compatible with itself.
- Source files need a header mentionning the copyright (the person(s) who wrote the code) + license information. You can see an example here: https://github.com/adrienverge/openfortivpn/blob/9a8c295/src/config.c#L1-L16

**Comment by theinvisible** [comment]
Hi,

thanks, of course it should be GPL version 3 and i will adjust this asap.

Regards
Rene

**Comment by adrienverge** [comment]
Thank you!
