### ISSUE TITLE
Support for two-factor authentication

### ISSUE THREAD

**Issue by smares** [theinvisible/openfortigui#4]
Now that openfortivpn supports two-factor authentication, any chance we can see support added in openfortigui?

**Comment by theinvisible** [comment]
Thats on the todo list but will take some time.

We dont us TFA so i have to setup a proper test-environment first. Also the original openfortivpn is designed for single VPN and terminal use only. OpenFortiGUI can use multiple VPNs simultaneously and a GUI. Also i dont want to modify the upstream openfortivpn code if not really required. For this feature it is required to install some hooks in the openfortivpn code to intercept the TFA input.

**Comment by boospy** [comment]
> OpenFortiGUI can use multiple VPNs simultaneously and a GUI. Also i dont want to modify the upstream openfortivpn code if not really required.
I agree with!

**Comment by theinvisible** [comment]
2FA/OTP is now supported in latest version 0.3.0 and above. Please give it a try and leave feedback: https://hadler.me/2017/07/openfortigui-0-3-0/
