### ISSUE TITLE
Resolving Local DNS

### ISSUE THREAD

**Issue by Phil-ThePower-Pearce** [theinvisible/openfortigui#40]
I have the latest version 0.6.2, when Im on the LAN I can resolve the DNS names, when I am working from home on the VPN connection, I can ping the IP addresses but not resolve them.

The nameservers are specified in resolv.conf.  Is there a way to specify the nameservers in the vpn config?

**Comment by theinvisible** [comment]
Hi,

the nameservers are always pulled from your Fortigate if configured properly. Also make sure you enabled the option in your OpenFortiGUI VPN profile to set the DNS.

Cheers
Rene

**Comment by Pilly170** [comment]
the fortigate is not propagating the resolv.conf  search details

**Comment by theinvisible** [comment]
Thats true but not really a OpenFortiGUI problem. It should still work with FQDN when DNS is set properly.
