### ISSUE TITLE
port is not stored in vpn profile

### ISSUE THREAD

**Issue by reutsharabani** [theinvisible/openfortigui#47]
I've attempted to create a (local) vpn profile with a specific port number. The moment I exit the application and re-run it the port is re-set to 1.

Any idea where this is coming from?

I can look into it but my cpp is pretty rusty.

**Comment by theinvisible** [comment]
Hi,

can you give exact instructions how to reproduce your problem?

I can not verify this here, what OS are your using?

Regards
Rene

**Comment by reutsharabani** [comment]
@theinvisible sorry for the lack of response. I'm using Ubuntu LTS 18.04 with `openfortigui -v` output:

    openfortiGUI 0.7.0

I just created a local vpn profile under `local vpns` and configured it. Everything was persisted and properly loaded but the vpn port (reset to 1). I tried it a few times and this is the only one that didn't stick. If you need more info let me know.

If I can somehow debug this myself through a log let me know as well.

**Comment by reutsharabani** [comment]
Added a PR to fix this: https://github.com/theinvisible/openfortigui/pull/54

**Comment by theinvisible** [comment]
Thanks, this fix was merged now and is included in next release.
