### ISSUE TITLE
Saved passwords not working since 0.7.0 update?

### ISSUE THREAD

**Issue by tsundeoku** [theinvisible/openfortigui#49]
Since updating to openfortigui 0.7.0, saving passwords in the VPN configuration no longer works. If I enter a password into the VPN configuration, as I did in 0.6.2, attempting to connect fails almost immediately with "ERROR:  Could not authenticate to gateway (Bad HTTP response code)." in the log. If I remove the password from the configuration and attempt to connect, I am prompted for the password each time and can connect normally. Could this be related to the changes in password handling?

**Comment by theinvisible** [comment]
Hi, 

the last change in password handling was made from version 0.5.x to 0.6. The password encryption handling was switched to openssl at this time.

Also i dont know of any problems with password handling. 

Regards
Rene

**Comment by boospy** [comment]
Password handling working fine. So closed :+1:
