### ISSUE TITLE
When VPN is connected all traffic goes over this connection

### ISSUE THREAD

**Issue by brandony-pn** [theinvisible/openfortigui#51]
When I establish a vpn connection configured with OpenFortiGUI all traffic ends up getting routed over that connection. This is not desirable given the restrictive network configuration of that connection. How can I configure the vpn connection to only route traffic for resources on that network over the vpn and allow all other traffic to be serviced through my local network?

**Comment by theinvisible** [comment]
Hi,

this is a setting on your Fortigate called "Split Tunneling" and must be enabled and configured on your Fortigate. By default all traffic ist routed trough the VPN tunnel.
