### ISSUE TITLE
Install from ppa fails because of libssl1.0.2 missing on Ubuntu 18.04

### ISSUE THREAD

**Issue by straussCS** [theinvisible/openfortigui#55]
I follwed the instructions on https://apt.iteas.at/ and ran 'apt update' afterwards.

When trying to install openfortigui I am recieving the following error.

```
$ sudo apt install openfortigui
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 openfortigui : Depends: libssl1.0.2 (>= 1.0.2d) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

When checking the installed packages it seems that a package libssl1.0.0 with version 1.0.2n is available and already installed.

```
$ apt search libssl1
Sorting... Done
Full Text Search... Done
libssl1.0-dev/bionic-updates,bionic-security 1.0.2n-1ubuntu5.1 amd64
  Secure Sockets Layer toolkit - development files

libssl1.0.0/bionic-updates,bionic-security,now 1.0.2n-1ubuntu5.1 amd64 [installed,automatic]
  Secure Sockets Layer toolkit - shared libraries

libssl1.1/bionic-updates,bionic-security,now 1.1.0g-2ubuntu4.1 amd64 [installed]
  Secure Sockets Layer toolkit - shared libraries
```

**Comment by theinvisible** [comment]
Hi, we have several 18.04 machines here and and I am also testing on a fresh 18.04 installation VM but could never experience this issue. Do you have any other deb/PPA-Repo included in your system?

**Comment by straussCS** [comment]
@theinvisible Thanks for your reply. I was able to reproduce the very same error in an pristine (and up2date) ubuntu 18.04.1 VM. 

The .deb downloaded from https://hadler.me/linux/openfortigui/ did work fine for me, tough.

**Comment by straussCS** [comment]
@theinvisible you are right, it was set to stretch. This fixed the error for me, thank you ;)
