### ISSUE TITLE
How to avoid DNS being modified

### ISSUE THREAD

**Issue by adriangibanelbtactic** [theinvisible/openfortigui#59]
My system:
*  Version: 0.7 (Package)
* OS: Debian GNU/Linux 9 with SystemD

How to reproduce the bug:
* Create a VPN entry
* Edit the VPN entry:
1) Set DNS: Unchecked
2) PPD no peerdns: Checked
* Save connection
* Connect the VPN entry

Expected behaviour
/etc/resolv.conf is not modified at all
Found behaviour
/etc/resolv.conf is modified

Thank you very much for any feedback you can give me.

P.S.: I know my problem is quite similar to https://github.com/theinvisible/openfortigui/issues/41 but I think it's a different one because I don't want the openfortigui dns settings to be kept but not to be used at all.

**Comment by adriangibanelbtactic** [comment]
> I dont have a Debian 9 test machine here right now. I will install a Debian 9 VM later.

For this specific problem I think Ubuntu 16.04 might be equivalent (just in case it might avoid you installing a Debian 9 VM)

**Comment by angela-d** [comment]
@adriangibanelbtactic  I had the opposite problem :smile: 

If you do not want /etc/resolv.conf touched:
```bash
chattr +i /etc/resolv.conf 
```

This will also prevent you or Network Manager from modifying it, until you remove the lock.  If you want to change it later on, or give Network Manager ability to modify it once again:
```bash
chattr -i /etc/resolv.conf 
```

**Comment by adriangibanelbtactic** [comment]
> @adriangibanelbtactic I had the opposite problem 
> 
> If you do not want /etc/resolv.conf touched:
> 
> ```shell
> chattr +i /etc/resolv.conf 
> ```

That's not a proper solution for me but thank you for the possible workaround.

**Comment by adriangibanelbtactic** [comment]
> Any strange error messages in OpenFortiGUI/VPN Log (Debug enabled) or system log?

File: /home/USER/.openfortigui/logs/vpn/MYVPN.log
(Upon connecting)
```
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
INFO:   Got addresses: [10.212.134.200], ns [172.16.2.60, 172.16.2.61]
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
WARN:   Route to gateway exists already.
INFO:   Tunnel is up and running.
```

File: /home/USER/.openfortigui/logs/openfortigui.log
(Upon connecting)
```
ene. 8 17:50:05 openfortiGUI::Debug: active-tab:: 0
ene. 8 17:50:05 openfortiGUI::Debug: start vpn: "MYVPN" active-tab:: 0
ene. 8 17:50:05 openfortiGUI::Debug: Start vpn:: "MYVPN"
ene. 8 17:50:05 openfortiGUI::Debug: add logger "/home/USER/.openfortigui/main.conf"
ene. 8 17:50:05 openfortiGUI::Debug: vpnManager::onClientConnected()
ene. 8 17:50:05 openfortiGUI::Debug: client api helo command:: 0 ::name:: "MYVPN"
ene. 8 17:50:05 openfortiGUI::Debug: 1546966205757 bytes avail:: 97
ene. 8 17:50:05 openfortiGUI::Debug: 1546966205957 bytes avail:: 71
ene. 8 17:50:05 openfortiGUI::Debug: vpnManager::onClientVPNStatusChanged() "MYVPN" status 1
ene. 8 17:50:05 openfortiGUI::Debug: MainWindow::onClientVPNStatusChanged:: "MYVPN" ::status:: 1
ene. 8 17:50:08 openfortiGUI::Debug: vpnManager::onClientVPNStatusChanged() "MYVPN" status 2
ene. 8 17:50:08 openfortiGUI::Debug: MainWindow::onClientVPNStatusChanged:: "MYVPN" ::status:: 2
ene. 8 17:50:08 openfortiGUI::Debug: 1546966208079 bytes avail:: 135
```

@theinvisible . Debug is enabled on. Do you need more logs that I am unaware of?

Thank you.

**Comment by boospy** [comment]
Same problem here on Ubuntu 18.04.

**Comment by adriangibanelbtactic** [comment]
@boospy : Can you please enable debug and share with us the specific parts of:
 - /home/USER/.openfortigui/logs/vpn/MYVPN.log
 - /home/USER/.openfortigui/logs/openfortigui.log

that @theinvisible asked me ?

Thank you.

**Comment by boospy** [comment]
I've talked today to the dev. He analyse this on my logs.

**Comment by theinvisible** [comment]
Is this issue still present with current versions? There were a lot of DNS related updates in openfortivpn. Also keep in mind DNS is setup by openfortivpn itself, so maybe its better to create a ticket there. Thanks.

**Comment by aman0019** [comment]
I am still seeing the same behavior on 18.04; I can provide logs if required just wondering if this had indeed been resolved

**Comment by aman0019** [comment]
for the record; I updated to latest openfortigui (0.9.2), set BOTH Set DNS: Unchecked & PPD no peerdns: Checked. And the problem went away. Thanks
