### ISSUE TITLE
Openfortigui in Ubuntu 18.10 development version

### ISSUE THREAD

**Issue by wagafo** [theinvisible/openfortigui#61]
I'm using the upcoming Ubuntu 18.10 version (still in development) and Openfortigui is not connecting. It shows successful connection, but the VPN tunnel is not established.

**Comment by cdysthe** [comment]
So there's not going to be support for any full releases outside of LTSs like 18.10, 19,04 and 19.10? I have to upgrade for work and need OpenFortiGUI for that work. Not sure what to do.

**Comment by wagafo** [comment]
Openfortigui is nice, but now Fortifvpn is integrated into network-manager. I'm working with that in 18.10. Just install:
sudo apt install openfortivpn network-manager-fortisslvpn network-manager-fortisslvpn-gnome
and you can configure the connection in the VPN section of network-manager.
Of course I would love to go back to Openfortigui if it can be fixed for Ubuntu 18.10. I can connect the high latency case that I have with Openfortigui but I cannot with network-manager because it times out waiting for a handshake or something and I have not been able to increase this timeout. There I can connect with 
sudo openfortivpn
but somehow the DNS does not work for the VPN network, I have to use IP numbers.

**Comment by theinvisible** [comment]
Hi,

i have now made a quick test in Virtualbox with 18.10.

I used openFortiGUI 0.7.2 bionic release and my test vpn was immediately working. Also traffic to the test vpn was working.

@cdysthe
Normally the LTS releases also works on newer Ubuntus without modifications as i did my test on 18.10 with bionic release package.

@rhaamo 
Seems like an generic authentication failure. Sure all was set up correct?

Cheers
Rene

**Comment by theinvisible** [comment]
Hi,

you can try the latest version.

Will still close this as Ubuntu 19.04 is out and generally i dont give support for non LTS releases.
