### ISSUE TITLE
Version 0.7.1 not in the APT mirror

### ISSUE THREAD

**Issue by pachulo** [theinvisible/openfortigui#62]
I'm using the apt mirrot https://apt.iteas.at/ and the update to 0.7.1 still did not show up.

**Comment by theinvisible** [comment]
Which OS are you using?

The packages are available for Ubuntu 16.04 32/64bit, 18.04 64bit and Debian 9 64bit.

https://apt.iteas.at/iteas/pool/main/o/openfortigui/

Cheers

**Comment by pachulo** [comment]
I'm using Ubuntu 16.04 so I'm not really sure why it did not work; anyway it does now. Thanks!

**Comment by pachulo** [comment]
The problem was that I still had configured the old repo:

- http://styrion.at/apt
