### ISSUE TITLE
OpenFortiGUI not able to use Gnome Keyring in Ubuntu 18.10

### ISSUE THREAD

**Issue by cdysthe** [theinvisible/openfortigui#63]
We just updated to Ubuntu 18.10. OpenFortiGUI does work, but not able to use Gnome Keyring. If I try check the box I'm told that the password manager isn't working:

`Password manager ist not working, please check the status on your system (GNOME Keyring or KWallet). Error message: Unknown error`

It works with other applications. Could this be fixed?

**Comment by cdysthe** [comment]
i'm ashamed. I didn't read down. Three libraries were missing on 18.10 as indicated in another issue. With them installed it's all good. Sorry!

**Comment by homberger** [comment]
> Three libraries were missing on 18.10 as indicated in another issue. With them installed it's all good.

Which libraries were missing?
