### ISSUE TITLE
connect using just a certificate

### ISSUE THREAD

**Issue by claudiuion** [theinvisible/openfortigui#65]
I'm trying to connect to a VPN server using only a certificate (no user, no password). I hit connect and the login pop-up appears
![login](https://user-images.githubusercontent.com/30018506/47951382-9db0c280-df68-11e8-86de-299328ce6084.png)
After i click submit the status changes to Connecting
![connecting](https://user-images.githubusercontent.com/30018506/47951442-74dcfd00-df69-11e8-81e6-ef0b813e38a3.png)
 but after waiting for half an hour still nothing happens. Can you look into this? 
My company uses only certificates for authentication. 
On Windows machines using the official Forti client, the connection works after selecting the certificate from the drop down list.

Thank you.

**Comment by theinvisible** [comment]
Hi, does it work with openfortivpn? Also whats the log output for the specified VPN? Thanks and cheers Rene

**Comment by theinvisible** [comment]
Thanks, as OpenFortiGUI is using openfortivpn as its core, this problem must be solved first in openfortivpn. I will close this ticket until there is some progress or solution available.
