### ISSUE TITLE
Segmentation Fault on Ubuntu 18.04

### ISSUE THREAD

**Issue by piotrppe** [theinvisible/openfortigui#66]
This issue happens only during heavy "load" - ie. when big amount of data is being pushed thorugh VPN (eg. - database dump) - after 1-2 gigabytes I get segmentation fault error.
From dmesg:
[23820.367539] QThread[6600]: segfault at 7ff690018880 ip 00007ff62196c71b sp 00007ff60f7fd540 error 4 in libQt5Core.so.5.9.5[7ff62184e000+53b000]

openFortiGUI 0.7.1

**Comment by theinvisible** [comment]
Hi,

first update to latest version 0.7.2.2

If the error still occurs please disable any debug in OpenFortiGUI. With debug enabled, every packet will be logged on system. With heavy traffic there were always some issues in the past.

**Comment by theinvisible** [comment]
Will close this in lack of respond.
