### ISSUE TITLE
feature request - support for pppd-ifname

### ISSUE THREAD

**Issue by gittela** [theinvisible/openfortigui#67]
can you add support for pppd-ifname? It would make custom pppd-scripts a lot easier if the tunnel interfaces have predictable names.

**Comment by theinvisible** [comment]
Hi, as OpenFortiGUI is only a GUI on top of openfortivpn this feature request should be submitted here: https://github.com/adrienverge/openfortivpn/issues

Thanks, will close this.

**Comment by gittela** [comment]
But that's the whole point! It's supported in openfortivpn, but not in the gui. The gui config files are not passing that option on to openfortivpn.
