### ISSUE TITLE
Establishing connection with openFortiGui on Fedora 29

### ISSUE THREAD

**Issue by msilberg** [theinvisible/openfortigui#68]
Hi,
Having managed to build openFortiGui binary from source on Fedora 29 I can finally run it, but still I'm not able to establish connection.
When I run the binary, having pressed Connect button, in the cli it asks me for my user's password (the operating system's, not the one of the connection) and when I input it nothing happens and the connection status is still disconnected.
Connection itself works and was tested on Ubuntu machine with openFortiGui.
Here are additional logs I found
`Dec 22 02:47:59 openfortiGUI::Info: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Dec 22 02:48:00 openfortiGUI::Warning: QMetaObject::connectSlotsByName: No matching signal for on_btnAddVPN_clicked()
Dec 22 02:48:00 openfortiGUI::Warning: QMetaObject::connectSlotsByName: No matching signal for on_btnDeleteVPN_clicked()
Dec 22 02:48:00 openfortiGUI::Warning: QMetaObject::connectSlotsByName: No matching signal for on_btnEditVPN_clicked()
Dec 22 02:48:00 openfortiGUI::Warning: QMetaObject::connectSlotsByName: No matching signal for on_btnCopyVPN_clicked()
Dec 22 02:48:00 openfortiGUI::Warning: QMetaObject::connectSlotsByName: No matching signal for on_btnAddGroup_clicked()
Dec 22 02:48:00 openfortiGUI::Warning: QMetaObject::connectSlotsByName: No matching signal for on_btnDeleteGroup_clicked()
Dec 22 02:48:00 openfortiGUI::Warning: QMetaObject::connectSlotsByName: No matching signal for on_btnEditGroup_clicked()
Dec 22 02:48:00 openfortiGUI::Warning: QMetaObject::connectSlotsByName: No matching signal for on_btnCopyGroup_clicked()
Dec 22 02:48:00 openfortiGUI::Warning: QObject::connect: No such signal vpnLogger::finished() in vpnmanager.cpp:46
Dec 22 02:48:00 openfortiGUI::Warning: QObject::connect: No such signal vpnLogger::finished() in vpnmanager.cpp:47
Dec 22 02:48:03 openfortiGUI::Warning: "QLocalSocket::connectToServer: Connection refused"
Dec 22 02:48:03 openfortiGUI::Warning: Socket not open
`
I'd appreciate if you  provide me with any other kind of information in order to resolve the issue.
Thanks.

**Comment by theinvisible** [comment]
Hi, I dont use Fedora so i cant really debug it, maybe someone else can try.

But it seems like the sudo files are missing. Please have a look here for an example: https://github.com/theinvisible/openfortigui/blob/master/openfortigui/sudo/openfortigui and adjust to your binary location of openfortigui

As the VPN tunnel can only be brought up with root permissions its necessary that the user who is running openfortigui can run it also with root permissions.

**Comment by fatihusta** [comment]
# Build openfortigui inside the container for fedora
I choose the podman. You can use the docker. Almost everything should be same.

Get fedora image from registery
`podman pull fedora:36`

Start a container as daemon mode
`podman run -itd --name fedora36 --hostname fedora36 fedora:36`

Enter inside the container
`podman exec -it fedora36 bash`

Install rpmbuild packages
`dnf install -y rpm-build rpmdevtools dnf-plugins-core git vim`

Create rpmbuild directories
`rpmdev-setuptree`

Create patch file
`vim  /root/rpmbuild/SOURCES/fedora_build.patch`

Copy these into patch file
```
diff -aur a/openfortigui/openfortivpn/src/tunnel.c b/openfortigui/openfortivpn/src/tunnel.c
--- a/openfortigui/openfortivpn/src/tunnel.c	2022-05-25 10:05:28.917411864 +0000
+++ b/openfortigui/openfortivpn/src/tunnel.c	2022-05-25 11:28:56.094620958 +0000
@@ -66,6 +66,7 @@
 #include <errno.h>
 #include <signal.h>
 #include <string.h>
+#include <bsd/string.h>
 #include <assert.h>
 
 
@@ -677,7 +678,8 @@
 			          ifr.ifr_name);
 			goto err_post_socket;
 		}
-		ret = bind(handle, &ifr.ifr_addr, ifr.ifr_addr.sa_len);
+		//ret = bind(handle, &ifr.ifr_addr, ifr.ifr_addr.sa_len);
+		ret = bind(handle, &ifr.ifr_addr, sizeof(ifr.ifr_addr));
 #endif
 		if (ret) {
 			log_error("socket: setting interface name failed with error: %d\n",
diff -aur a/openfortigui/sudo/openfortigui b/openfortigui/sudo/openfortigui
--- a/openfortigui/sudo/openfortigui	2022-05-25 10:05:27.788409121 +0000
+++ b/openfortigui/sudo/openfortigui	2022-05-25 15:55:00.041025072 +0000
@@ -1 +1 @@
-%sudo  ALL=NOPASSWD:SETENV: /usr/bin/openfortigui --start-vpn *
+%wheel  ALL=NOPASSWD:SETENV: /usr/bin/openfortigui --start-vpn *
```


Create spec file
`vim  /root/rpmbuild/SOURCES/openfortigui.spec`

Copy these linse and paste into spec file.
```

%global debug_package %{nil}

%define	ofg_version 0.9.6
%define ofg_release 1

Name:           openfortigui
Version:        %{ofg_version}
Release:        %{ofg_release}%{?dist}
Summary:        OpenFortiGUI is an open-source VPN-Client to connect to Fortigate VPN-Hardware. 
Packager:	Fatih Usta <fatihusta86@gmail.com>

License:        GPLv3
URL:            https://hadler.me/linux/openfortigui
Source0:        %{name}-%{version}.tar.gz
Patch0:		fedora_build.patch

BuildRequires:  cmake, extra-cmake-modules
BuildRequires:  qt5-qtbase-devel, qtkeychain-qt5-devel
BuildRequires:  openssl-devel
BuildRequires:  systemd-devel
BuildRequires:  libbsd-devel

Requires:       ppp, redhat-lsb-core

%description
OpenFortiGUI is an open-source VPN-Client to connect to Fortigate VPN-Hardware.
It is based on openfortivpn and adds an easy to use and nice GUI on top of it,
written in Qt5.


%prep
%autosetup -p1


%build
export LDFLAGS="-lbsd"

cmake .
%make_build


%install
mkdir -p %{buildroot}/usr/bin
mkdir -p %{buildroot}/usr/share/applications
mkdir -p %{buildroot}/usr/share/pixmaps
mkdir -p %{buildroot}/etc/sudoers.d
mkdir -p %{buildroot}/usr/share/licenses/%{name}
cp -a bin/openfortigui %{buildroot}/usr/bin/
cp -a openfortigui/sudo/openfortigui %{buildroot}/etc/sudoers.d/
cp -a openfortigui/app-entry/openfortigui.desktop %{buildroot}/usr/share/applications/
cp -a openfortigui/app-entry/openfortigui.png %{buildroot}/usr/share/pixmaps/
cp LICENSE LICENSE.OpenSSL %{buildroot}/usr/share/licenses/%{name}

%files
%license /usr/share/licenses/%{name}/LICENSE*
%{_bindir}/openfortigui
%{_sysconfdir}/sudoers.d/openfortigui
%{_datadir}/applications/openfortigui.desktop
%{_datadir}/pixmaps/openfortigui.png


%changelog
* Wed May 25 2022 Fatih USTA <fatihusta86@gmail.com>
- Initial build

```

Define openfortigui version
`export version="0.9.6"`

Clone openfortigui with submodules
```
git clone -b v${version} \
    --single-branch \
    --recursive \
    --depth 1 \
    -j$(nproc) \
    https://github.com/theinvisible/openfortigui.git /root/rpmbuild/SOURCES/openfortigui-${version}

```
Create archive file for rpmbuild
```
tar -czvf /root/rpmbuild/SOURCES/openfortigui-${version}.tar.gz \
    --exclude=.git* \
    --exclude=krunner_openfortigui* \
    -C /root/rpmbuild/SOURCES \
    openfortigui-${version}

```
Install build requierment packages
`dnf builddep -y /root/rpmbuild/SOURCES/openfortigui.spec`

Define rpm release 
`export release="1"`

Build openfortigui rpm
```
rpmbuild -ba \
    --define "ofg_version ${version:-0.9.6}" \
    --define "ofg_release ${release:-1}" \
    /root/rpmbuild/SOURCES/openfortigui.spec
```

exit container or open new terminal

Copy rpm from container to host machine
`podman cp fedora36:/root/rpmbuild/RPMS/x86_64/openfortigui-0.9.6-1.fc36.x86_64.rpm /tmp`

# Install openfortigui rpm
`dnf install -y /tmp/openfortigui-0.9.6-1.fc36.x86_64.rpm`

**Make sure your user member of wheel group. (This is sudo user)**
`id`
`# uid=1000(fatih) gid=1000(fatih) groups=1000(fatih),10(wheel),978(vboxusers)`

**It should work now**

# Known issue;
  * If you started one time openfortigui with sudo, you should remove socket file(/tmp/openfortiGUI) and then run application again without sudo.
    Because that file owner is root. This socket will be create with your username when you started application again with your user.


# We still have some problems. 
I think those problem related with wayland.

May 25 19:11:29 openfortiGUI::Warning: QSocketNotifier: Can only be used with threads started with QThread
May 25 19:11:30 openfortiGUI::Warning: QMetaObject::connectSlotsByName: No matching signal for on_btnAddVPN_clicked()
May 25 19:11:30 openfortiGUI::Warning: QMetaObject::connectSlotsByName: No matching signal for on_btnDeleteVPN_clicked()
May 25 19:11:30 openfortiGUI::Warning: QMetaObject::connectSlotsByName: No matching signal for on_btnEditVPN_clicked()
May 25 19:11:30 openfortiGUI::Warning: QMetaObject::connectSlotsByName: No matching signal for on_btnCopyVPN_clicked()
May 25 19:11:30 openfortiGUI::Warning: QMetaObject::connectSlotsByName: No matching signal for on_btnAddGroup_clicked()
May 25 19:11:30 openfortiGUI::Warning: QMetaObject::connectSlotsByName: No matching signal for on_btnDeleteGroup_clicked()
May 25 19:11:30 openfortiGUI::Warning: QMetaObject::connectSlotsByName: No matching signal for on_btnEditGroup_clicked()
May 25 19:11:30 openfortiGUI::Warning: QMetaObject::connectSlotsByName: No matching signal for on_btnCopyGroup_clicked()
May 25 19:11:30 openfortiGUI::Warning: QObject::connect: No such signal vpnLogger::finished()
May 25 19:11:30 openfortiGUI::Warning: QObject::connect: No such signal vpnLogger::finished()
May 25 19:11:30 openfortiGUI::Warning: QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
May 25 19:11:34 openfortiGUI::Warning: Wayland does not support QWindow::requestActivate()
