### ISSUE TITLE
SSLVPN Connects but no route information where added to my routing table and no changes on GUI connection Icon.

### ISSUE THREAD

**Issue by fquiroga** [theinvisible/openfortigui#7]
Hi, 
I'm triying to connect to my appliance, i've download from git sources and complile successfully in my Debian 8. However the gui doesn't change from red icon to a green icon indicating that i was connected, researching in the logs i see that the tunnel is stablished, the interface ppp0 was added to my ifconfig but no correct route information where added to my routing table. 

This is my logs : 
tail -f connection.log 
Jul 9 17:52:43 openfortiGUI::Info: "start-vpn process::config_file::" "/root/.openfortigui/main.conf"
Jul 9 17:52:43 openfortiGUI::Info: vpnWorker::process::slot
Jul 9 17:52:43 openfortiGUI::Info: usercert:: 
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
INFO:   Custom: x.x.x.x.
INFO:   Got addresses: [x.x.x.x], ns [0.0.0.0, 0.0.0.0]
INFO:   Interface ppp0 is UP.
INFO:   Tunnel is up and running.

This is a picture of the gui: 

![selection_025](https://user-images.githubusercontent.com/17765503/27997593-f74c714e-64d1-11e7-9c21-91f3b1d98c7e.png)

This is information about route added in my Debian: 

1.1.1.1         0.0.0.0         255.255.255.255 UH    0      0        0 ppp0

The route is incorrect, i might publish 192.168.254.0/24 trough this interface, Windows FortiClient adds this route successfully. 

How can i get more informatio to debug this problem ?

**Comment by boospy** [comment]
Have you set the "set routes" Flag in the options per vpn?
For installtion you can also try us repository: http://styrion.at/apt/

**Comment by theinvisible** [comment]
Hello, any news here? If not i will close this issue.
