### ISSUE TITLE
Segmentationfault on incorrect user

### ISSUE THREAD

**Issue by Khartir** [theinvisible/openfortigui#71]
I got a segmentation fault trying to connect. However, realised this was due to an incorrect username. It works fine with the correct username.

Linux MInt 19.
dmesg:
openfortigui[6463]: segfault at 2b8 ip 000055cc33f7dc44 sp 00007fffd9d8bf08 error 4 in openfortigui[55cc33f35000+d9000]

**Comment by theinvisible** [comment]
Hi, please enable Debug on global settings and VPN and try again. Then see if you can find some hints in the log files. Thanks

**Comment by Khartir** [comment]
Unfortunatley I can no longer debug this issue, the Server has been shut down.
