### ISSUE TITLE
feature request - support for pppd-ifname again

### ISSUE THREAD

**Issue by gittela** [theinvisible/openfortigui#73]
This is the same request as #67

You replied that this was a request for openfortivpn, but the whole point is that it is already supported in the application itself. The options aren't passed on from the gui config to openfortivpn.

**Comment by theinvisible** [comment]
Oh, sorry, i mistaken this with another issue. Will have a look again.

**Comment by theinvisible** [comment]
Okay, your requested feature is now included in version 0.7.3, please feel free to try.

**Comment by gittela** [comment]
Awesome, I will give it a spin! I use this a lot to control traffic when the remote FGT is (mis)configured, not allowing split tunnel.
