### ISSUE TITLE
ERROR:  SSL_CTX_load_verify_locations

### ISSUE THREAD

**Issue by slc66** [theinvisible/openfortigui#75]
OS : Ubuntu 18.10
openfortigui version : 0.7.3

Hello,

Since 0.7.3, I'm unable to open connection. Here is a part of log :
```
INFO:   Start tunnel.
ERROR:  SSL_CTX_load_verify_locations: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
INFO:   Closed connection to gateway.
ERROR:  SSL_CTX_load_verify_locations: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
INFO:   Could not log out.
INFO:   Setting ppp interfac-ae down.
```
and my configuration

![Screenshot](https://slc66.myqnapcloud.com/pub/img/captures/logilec/20190305-OpenFortiGUI-EditVPN_001.png)

Do you have any idea about this issue ?

Best regards,

Stephane

**Comment by slc66** [comment]
Hi all,

Does anyone have an idea or an early runway ?

What can I check for working on a solution ?

Best regards

**Comment by theinvisible** [comment]
Hi,

this error should only appear when there is a CA set with a non existing path.

Can you post your vpnprofile from ~/.openfortigui/vpnprofiles, maybe there is still some value set.

Regards

**Comment by slc66** [comment]
Hi,
Here is my vpnprofile. I've delete user and password entries.

[Bureau.zip](https://github.com/theinvisible/openfortigui/files/2989704/Bureau.zip)

.

**Comment by theinvisible** [comment]
Looks okay so far. Do you use the latest version 0.7.3.1? On 0.7.3 was some bug when no CA-Cert was given, this was fixed in 0.7.3.1 .

**Comment by slc66** [comment]
Yes, I use the last version : 0.7.3.1.

**Comment by theinvisible** [comment]
You must add the sha256 digest to your VPN-profile config (Field trusted cert). In the latest git code and next version there is also a detection via GUI included.

**Comment by slc66** [comment]
I have filled Trusted-Cert with key found in logs when the error raise. Now it's running well.

Thx
