### ISSUE TITLE
Segfault in Ubuntu 18.10

### ISSUE THREAD

**Issue by CODeRUS** [theinvisible/openfortigui#76]
Hi! openfortigui was forking just fine two weeks ago, today after update it's  not working anymore.

```
Program received signal SIGSEGV, Segmentation fault.
vpnWorker::end (this=0x7ffff2282000) at proc/vpnworker.cpp:552
552         ptr_tunnel->on_ppp_if_down(ptr_tunnel);
(gdb) bt
#0  vpnWorker::end (this=0x7ffff2282000) at proc/vpnworker.cpp:552
#1  0x00005555555958cd in vpnProcess::closeProcess (this=0x7fffffffd110) at proc/vpnprocess.cpp:69
#2  0x0000555555595ba2 in vpnProcess::startVPN (this=0x7fffffffd110) at proc/vpnprocess.cpp:105
#3  0x000055555559577b in vpnProcess::run (this=0x7fffffffd110, vpnname=...) at proc/vpnprocess.cpp:62
#4  0x000055555556ae95 in main (argc=6, argv=0x7fffffffe528) at main.cpp:165
```

**Comment by CODeRUS** [comment]
ubuntu 18.10

Linux desktop 4.18.0-16-generic #17-Ubuntu SMP Fri Feb 8 00:06:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cdysthe** [comment]
Does it crash on open or connect?

**Comment by vgarcia-visionaip** [comment]
Can you please add the log content from the vpn connection? I had a similar issue in Ubuntu 16.04.
It should be on /home/user/.openfortigui/logs/vpn/VPNNAME.log

**Comment by CODeRUS** [comment]
> Can you please add the log content from the vpn connection? I had a similar issue in Ubuntu 16.04.
> It should be on /home/user/.openfortigui/logs/vpn/VPNNAME.log

Thanks! Log says:
```Gateway certificate validation failed, and the certificate digest in not in the local whitelist. If you trust it, rerun with:```

So i added sha cert to vpn config and now it's working!
