### ISSUE TITLE
feature request - support one time password in gui

### ISSUE THREAD

**Issue by gittela** [theinvisible/openfortigui#78]
Is it possible to add a dialogue/support for One Time Password in the gui? It is supported in openfortivpn by issuing "--otp 123456" when starting it (I get my key from the Fortitoken app).

**Comment by theinvisible** [comment]
Hi,

OTP should be autodetected if needed by fortigate and a popup window should appear.

If not please provide the log file so i can investigate.

**Comment by gittela** [comment]
Well, this is embarrassing... I didn't actually try it, I just assumed there would be an option somewhere that enabled it...
It works like a charm! Sorry for the wasted time. :-)
