### ISSUE TITLE
Process does not end after exiting in Linux Mint 19

### ISSUE THREAD

**Issue by bengordonfraser** [theinvisible/openfortigui#79]
Love your work.

Bug report: No system tray icon appears when running or hidden. Process does not end after exiting in Linux Mint 19.
OS: Linux Mint 19
System: Dell XPS-13 2.4GHz i7 16GB ram

**Comment by bengordonfraser** [comment]
I have just realised that there is a tray icon, it just isn't visible.

**Comment by theinvisible** [comment]
Hi, the program defaults to minimize to system tray. You can exit it via "File -> Exit" in program menu or via system tray -> exit.

**Comment by bengordonfraser** [comment]
Awesome, thank you. Resurrecting this for a brief followup: The program was indeed minimising to the system tray, but had no icon until I rebooted. This was the source of my confusion and inability to close the program. That is the only bug I have come across in a brilliant piece of software.
