### ISSUE TITLE
Add option to import trusted cert

### ISSUE THREAD

**Issue by xvybihal** [theinvisible/openfortigui#80]
Hi, would it be possible to add option to retrieve and import trusted certificate from this amazing gui?

I imagine it like this:
 1] add new connection
 2] try to connect first time
 3] I am asked if I trust this specific sha256 chakcsum of certificate
  3.1] If I press Accept, it is added as --trusted-cert

Now what I need to do is check the sha256 chaksum manually, dig to logs, etc. This would imho help be more user friendly.
Thanks

**Comment by theinvisible** [comment]
Hi,

this features is now included in latest git code and also on next release.
