### ISSUE TITLE
File has unexpected size (456644 != 455252).

### ISSUE THREAD

**Issue by radekskr** [theinvisible/openfortigui#84]
Hello,
 thank you for Openfortigui. I like it.

Can you please fix this issue:

When i try upgrade to the newest version 0.7.4-1:

The following packages will be upgraded: 
  openfortigui 
1 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 455 kB of archives. After unpacking 4 096 B will be freed.
Do you want to continue? [Y/n/?] 
Get: 1 https://apt.iteas.at/iteas bionic/main amd64 openfortigui amd64 0.7.4-1 [455 kB]
Err https://apt.iteas.at/iteas bionic/main amd64 openfortigui amd64 0.7.4-1
  File has unexpected size (456644 != 455252). Mirror sync in progress? [IP: 77.235.68.36 443]
Hashes of expected file:
 - SHA512:3cbec887e91f5666eb89f5eb733c85c27deb385307e7266a352f60242bc14e9a47885eaa0cc14129b7636e1d52213ee93b0139b47e94c3eac5156a5adadba077
 - SHA256:f4f7f006c0a6194ba29561373582f13b44bda3d9d0c89a49ade0e11df4c9fda2
 - SHA1:0e72853ff17d35989873b3b77297dc52c972a1d0 [weak]
 - MD5Sum:76234b0f2ece17b1c50422b7d85f1bd3 [weak]
 - Filesize:455252 [weak]

0% [Working]E: Failed to fetch https://apt.iteas.at/iteas/pool/main/o/openfortigui/openfortigui_0.7.4-1_amd64_bionic.deb: File has unexpected size (456644 != 455252). Mirror sync in progress? [IP: 77.235.68.36 443]
   Hashes of expected file:
    - SHA512:3cbec887e91f5666eb89f5eb733c85c27deb385307e7266a352f60242bc14e9a47885eaa0cc14129b7636e1d52213ee93b0139b47e94c3eac5156a5adadba077
    - SHA256:f4f7f006c0a6194ba29561373582f13b44bda3d9d0c89a49ade0e11df4c9fda2
    - SHA1:0e72853ff17d35989873b3b77297dc52c972a1d0 [weak]
    - MD5Sum:76234b0f2ece17b1c50422b7d85f1bd3 [weak]
    - Filesize:455252 [weak]
E: Unable to fetch some packages; try '-o APT::Get::Fix-Missing=true' to continue with missing packages

I can download manualy:

wget https://apt.iteas.at/iteas/pool/main/o/openfortigui/openfortigui_0.7.4-1_amd64_bionic.deb
--2019-05-31 11:51:26--  https://apt.iteas.at/iteas/pool/main/o/openfortigui/openfortigui_0.7.4-1_amd64_bionic.deb
Resolving apt.iteas.at (apt.iteas.at)... 77.235.68.36
Connecting to apt.iteas.at (apt.iteas.at)|77.235.68.36|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 456644 (446K) [application/x-debian-package]
Saving to: ‘openfortigui_0.7.4-1_amd64_bionic.deb.1’
openfortigui_0.7.4-1_amd64_bionic.deb.1   100%[===================================================================================>] 445,94K  1,44MB/s    in 0,3s    
2019-05-31 11:51:27 (1,44 MB/s) - ‘openfortigui_0.7.4-1_amd64_bionic.deb.1’ saved [456644/456644]

ls -l openfortigui_0.7.4-1_amd64_bionic.deb
-rw-r--r-- 1 root root 456644 kvě 25 18:32 openfortigui_0.7.4-1_amd64_bionic.deb

The file has size 456644 bytes.

But size of the file (455252) is different in file "Packages" in repository
https://apt.iteas.at/iteas/dists/bionic/main/binary-amd64/Packages
Maybe it is the mistake:

Package: openfortigui
Priority: optional
Section: admin
Installed-Size: 1136
Maintainer: Rene Hadler <rene@hadler.me>
Architecture: amd64
Version: 0.7.4-1
Provides: openfortigui
Depends: libc6 (>= 2.15), libgcc1 (>= 1:3.0), libqt5core5a (>= 5.9.0~beta), libqt5gui5 (>= 5.0.2), libqt5keychain1 (>= 0.7.0), libqt5network5 (>= 5.0.2), libqt5widgets5 (>= 5.2.0~alpha1), libssl1.1 (>= 1.1.0), libstdc++6 (>= 5.2), sudo, qttranslations5-l10n, ppp
Filename: pool/main/o/openfortigui/openfortigui_0.7.4-1_amd64_bionic.deb
Size: 455252
MD5sum: 76234b0f2ece17b1c50422b7d85f1bd3
SHA1: 0e72853ff17d35989873b3b77297dc52c972a1d0
SHA256: f4f7f006c0a6194ba29561373582f13b44bda3d9d0c89a49ade0e11df4c9fda2
SHA512: 3cbec887e91f5666eb89f5eb733c85c27deb385307e7266a352f60242bc14e9a47885eaa0cc14129b7636e1d52213ee93b0139b47e94c3eac5156a5adadba077
Description: GUI for openfortivpn

Thank you.
RadekSkr

**Comment by theinvisible** [comment]
Thanks for your report, should be fixed now. 

Regards
Rene

**Comment by radekskr** [comment]
Now it is ok. Thank very you much. RadekSkr.
