### ISSUE TITLE
Two Factor authentication not working for radius type authentication

### ISSUE THREAD

**Issue by absmith82** [theinvisible/openfortigui#85]
we are testing out a cloud 2fa system that uses radius to authenticate and have 2fa on the fortigate.  When using 2fa through this type of system the openfortigui does not prompt for the OTP.  I checked using the fortigate client as well as the openfortivpn cli client and both of these work as expected.  I assume the problem is something with the openfortigui receiving a slightly different OTP message. on openfortivpn after entering my password this is the cli prompt that I get

Please enter one-time password:

2fa that is enabled directly from the fortigate gets this message from the script

Two-factor authentication token:

**Comment by theinvisible** [comment]
Hi,

thats true, the prompt for OTP is triggered by keywords from openfortivpn output.

As you can see in vpnlogger.cpp your mentioned keywords should already be recognized by OpenFortiGUI. Maybe you can send the relevant output from OpenFortiGUI (just rightclick the specific VPN and click Logs) and post it here.

Cheers

**Comment by absmith82** [comment]
These are the only logs that I get

> INFO:   Start tunnel.
INFO:   Connected to gateway.

**Comment by theinvisible** [comment]
Please enable debug mode in settings and vpn profile and try again, should be alot more verbose.

**Comment by absmith82** [comment]
this is all the more info I received.  for reference the server and gateway address and ports are correct.

INFO:   Start tunnel.
DEBUG:  server_addr: <removed>
DEBUG:  server_port: <removed>
DEBUG:  gateway_addr: <removed>
DEBUG:  gateway_port: <removed>
DEBUG:  Gateway certificate validation succeeded.
INFO:   Connected to gateway.

**Comment by tiagolo** [comment]
This is also happening to me, with version 0.7.3.1 I'm able to connect to my VPN, but with 0.8.0 an OTP Token is show and before a can type anything the connection is closed.

This is the main debug log:
```
ago 5 11:16:20 openfortiGUI::Debug: active-tab:: 0
ago 5 11:16:20 openfortiGUI::Debug: start vpn: "MVRec - vpn" active-tab:: 0
ago 5 11:16:20 openfortiGUI::Debug: Start vpn:: "MVRec - vpn"
ago 5 11:16:20 openfortiGUI::Debug: Start vpn:: "MVRec - vpn"
tigui/main.conf"
ago 5 11:16:20 openfortiGUI::Debug: "start-vpn process::" "MVRec - vpn"
ago 5 11:16:20 openfortiGUI::Debug: "start-vpn process::config_file::" "/root/.openfortigui/main.conf"
ago 5 11:16:20 openfortiGUI::Debug: vpnProcess::startVPN::slot
ago 5 11:16:20 openfortiGUI::Debug: vpnManager::onClientConnected()
ago 5 11:16:20 openfortiGUI::Debug: client api helo command:: 0 ::name:: "MVRec - vpn"
ago 5 11:16:20 openfortiGUI::Debug: tiConfVpnProfile::readVpnProfiles() -> vpnprofile found: "/root/.openfortigui/vpnprofiles/MVRec - vpn.conf"
ago 5 11:16:20 openfortiGUI::Debug: tiConfVpnProfile::readVpnProfiles() -> vpnprofile found: "/root/.openfortigui/vpnprofiles/MVRec - vpn1.conf"
ago 5 11:16:20 openfortiGUI::Debug: tiConfVpnProfile::readVpnProfiles() -> vpnprofile found: "/root/.openfortigui/vpnprofiles/MVRec - vpn2.conf"
ago 5 11:16:20 openfortiGUI::Debug: tiConfVpnProfile::readVpnProfiles() -> vpnprofile found: "/root/.openfortigui/vpnprofiles/MVFor.conf"
ago 5 11:16:20 openfortiGUI::Debug: vpnWorker::process::slot
ago 5 11:16:21 openfortiGUI::Debug: 1565014581042 bytes avail:: 22
ago 5 11:16:21 openfortiGUI::Debug: vpnProcess::onObserverUpdate::status_update "MVRec - vpn" state 1
ago 5 11:16:21 openfortiGUI::Debug: vpnProcess::onObserverUpdate::status_update2 "MVRec - vpn" state 1
ago 5 11:16:21 openfortiGUI::Debug: vpnManager::onClientVPNStatusChanged() "MVRec - vpn" status 1
ago 5 11:16:21 openfortiGUI::Debug: MainWindow::onClientVPNStatusChanged:: "MVRec - vpn" ::status:: 1
ago 5 11:16:21 openfortiGUI::Debug: 1565014581374 bytes avail:: 30
ago 5 11:16:21 openfortiGUI::Debug: 1565014581578 bytes avail:: 23
ago 5 11:16:21 openfortiGUI::Debug: 1565014581796 bytes avail:: 44
ago 5 11:16:22 openfortiGUI::Debug: shutting down vpn process:: "MVRec - vpn"
ago 5 11:16:22 openfortiGUI::Debug: 1565014582342 bytes avail:: 470
ago 5 11:16:22 openfortiGUI::Debug: otprequest from vpnmanager
ago 5 11:16:22 openfortiGUI::Debug: 1565014582743 bytes avail:: 20
ago 5 11:16:24 openfortiGUI::Warning: QThread::start: Thread termination error: Processo inexistente
ago 5 11:16:24 openfortiGUI::Debug: client disconnected:: "MVRec - vpn"
ago 5 11:16:24 openfortiGUI::Debug: vpnManager::onClientVPNStatusChanged() "MVRec - vpn" status 0
ago 5 11:16:24 openfortiGUI::Debug: MainWindow::onClientVPNStatusChanged:: "MVRec - vpn" ::status:: 0
```

**Comment by tiagolo** [comment]
So, after updating my kernel from 4.19 to 5.2.5 and cleaning up all certificates It worked fine again.

**Comment by theinvisible** [comment]
Good to hear, will close this.
