### ISSUE TITLE
No DNS beeing populated on Ubuntu 17.04

### ISSUE THREAD

**Issue by tdmike** [theinvisible/openfortigui#9]
Hey,

I just installed the OpenFortiGui and after setting up multiple VPN's I noticed when I was connected my DNS server was set to 127.0.0.53 and none of the DNS server of the remote networks was beeing populated to my device. I could not find anything in the logs directly tied to this problem. The connection itself works fine since I can connect to device on that network on IP bases and the DNS servers are beeing populated when I connect with my other devices.

If you need any logging just ask I will try and find it for you

**Comment by theinvisible** [comment]
Hello, this is fixed now in the latest release (0.3.3.).

**Comment by tdmike** [comment]
Just tested it, works fine.
