### ISSUE TITLE
Terminated Connected With Invalid Log File

### ISSUE THREAD

**Issue by rcalixte** [theinvisible/openfortigui#91]
When a connection is created with a log file option that does not exist, rather than attempting to create the log file or using another writable fallback, the connect instead is terminated with a failure message about not being able to write the log file.

This should probably be a warning rather than something that prevents an otherwise valid connection from going through.

**Comment by theinvisible** [comment]
Thanks, will look into this.

**Comment by theinvisible** [comment]
Better error handling now in latest commit and next release
