### ISSUE TITLE
Openfortigui crashes when cloning a git repo (Ubuntu 19.04)

### ISSUE THREAD

**Issue by yourithielen** [theinvisible/openfortigui#93]
When cloning a git repo openfortigui often (intermittent) crashes:

![Screenshot from 2019-10-16 10-04-25](https://user-images.githubusercontent.com/2210373/66900188-a45f0b00-effc-11e9-8c1a-d866a35b45c2.png)
![Screenshot from 2019-10-16 10-04-40](https://user-images.githubusercontent.com/2210373/66900190-a4f7a180-effc-11e9-86ed-ec22d2cd595c.png)

**Comment by theinvisible** [comment]
Hi,

do you mean git clone over the SSLVPN?

If yes try to disable Debug log in main menu and VPN profile and test again.

**Comment by yourithielen** [comment]
> Hi,
> 
> do you mean git clone over the SSLVPN?
> 
> If yes try to disable Debug log in main menu and VPN profile and test again.

Yes, the main debug was enabled as well as the VPN debug. Disabled them both for now and will do some testing, will post results later.

**Comment by yourithielen** [comment]
Not experiencing any problems anymore, git clones are also a lot faster now the debug is disabled.
