### ISSUE TITLE
Error establishing a database connection on hadler.me

### ISSUE THREAD

**Issue by Vincent14** [theinvisible/openfortigui#95]
The website is down while software is broken on Ubuntu 19.10, we're on fire here! :)

**Comment by phptek** [comment]
Just spotted this myself and reported it to the maintainer. Is there even a release for 19.10? Latest as of yesterday was for Bionic.

**Comment by theinvisible** [comment]
Hi,
thanks, its fixed. ; )

As I already mentioned a few times i only support Ubuntu LTS releases originally. Debian and "short-time" Ubuntu releases are not really tested and supported. But if the community helps me testing and find bugs that are also likely to be in next LTS releases i am  always happy for some bug reports.
