### ISSUE TITLE
File has unexpected size (457328 != 456960)

### ISSUE THREAD

**Issue by pierluigi-passaro** [theinvisible/openfortigui#96]
Hi,
any chance you could fix the following size mismatch?
The package is present in the repo and is correctly downloaded as
   https://apt.iteas.at/iteas/pool/main/o/openfortigui/openfortigui_0.8.1-1_amd64_bionic.deb
but with a different size from what descibed in file
   https://apt.iteas.at/iteas/dists/bionic/main/binary-amd64/Packages
Following the output of an "apt upgrade".
Thanks
Regards
Pierluigi
---------
The following packages will be upgraded:
  openfortigui
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 457 kB of archives.
After this operation, 4.096 B of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 https://apt.iteas.at/iteas bionic/main amd64 openfortigui amd64 0.8.1-1 [457 kB]
Err:1 https://apt.iteas.at/iteas bionic/main amd64 openfortigui amd64 0.8.1-1
  File has unexpected size (457328 != 456960). Mirror sync in progress? [IP: 77.235.68.36 443]
  Hashes of expected file:
   - SHA512:c988770b00a0ec5a1def96ddc191741f47fbaf43a61f45829c457ba6edead4639c44ee7366e0f996b156bb0c6e0f6aa568076a646cbf1c47284fb4ae5d8b3839
   - SHA256:797cb5fee370ebe2393f0d8ec6de79fcc322c4e58eecc3bf38a249b7a90e8da6
   - SHA1:09a290f80bca53229e7f2293f6757db23412fb0b [weak]
   - MD5Sum:b91180f0467ee74c834c0a8bc599f752 [weak]
   - Filesize:456960 [weak]
E: Failed to fetch https://apt.iteas.at/iteas/pool/main/o/openfortigui/openfortigui_0.8.1-1_amd64_bionic.deb  File has unexpected size (457328 != 456960). Mirror sync in progress? [IP: 77.235.68.36 443]
   Hashes of expected file:
    - SHA512:c988770b00a0ec5a1def96ddc191741f47fbaf43a61f45829c457ba6edead4639c44ee7366e0f996b156bb0c6e0f6aa568076a646cbf1c47284fb4ae5d8b3839
    - SHA256:797cb5fee370ebe2393f0d8ec6de79fcc322c4e58eecc3bf38a249b7a90e8da6
    - SHA1:09a290f80bca53229e7f2293f6757db23412fb0b [weak]
    - MD5Sum:b91180f0467ee74c834c0a8bc599f752 [weak]
    - Filesize:456960 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by theinvisible** [comment]
Its fixed, please resync and try again

**Comment by pierluigi-passaro** [comment]
faster then the light ;)
Thanks!
