### ISSUE TITLE
Pressing "Quit app" before disconnecting hangs GNOME Shell

### ISSUE THREAD

**Issue by eloydegen** [theinvisible/openfortigui#97]
Sometimes it will hang GNOME Shell, otherwise GNOME Shell will detect something is wrong and restarts itself.

I'm using openFortiGUI 0.8.0 and GNOME Shell on Ubuntu 19.04

![VPN](https://user-images.githubusercontent.com/3866292/67926122-7dd0d080-fbb5-11e9-9546-33929bf2b9c8.png)

**Comment by eloydegen** [comment]
@theinvisible any logs I can provide that will help you with debugging?

**Comment by theinvisible** [comment]
Hi, you can enable debug log in main preferences and your vpn profile and check your logs if this happens again. If there is something suspected please post here.
