### ISSUE TITLE
Better feedback on connection problems

### ISSUE THREAD

**Issue by Zireael07** [theinvisible/openfortigui#98]
I am currently facing a problem connecting to my workplace's VPN. Alas, it's next to impossible to figure out what went wrong.
1) The GUI should tell you where to look for log files
2) The program should show you a message on failed connections, telling you why (DNS resolution failed, HTTPS not responding, certificate rejected, etc etc.)

**Comment by theinvisible** [comment]
Hi,

thanks for your feedback.

1. Its already accessible via GUI, the main log via "File -> Logs" and the VPN specific logs via "Right click VPN item -> View logs"
2. Thats indeed a good point for further enhancements. But keep in mind that even the big players in the market never provide good error messages. The messages are most of time only very generic ones and must also be investigated in more detail via log files. Of course thats not an excuse to make better, i will keep this as feature request.

**Comment by Zireael07** [comment]
Whoa, I'd've never guessed the right click one! Thanks, that's one problem solved.
